## 











Key properties of numpy :---ndim,shape,size,dtype

# Pandas

In [12]:
import pandas as pd
p=pd.Series([10,20,30,40])
print(p)

0    10
1    20
2    30
3    40
dtype: int64

In [13]:
data={
    "name":["A","B","C"],
    "number":[4,3,2]
}
df=pd.DataFrame(data)
print(df)

  name  number
0    A       4
1    B       3
2    C       2

In [14]:
df = pd.read_csv("products.csv")
print(df)

                                        title    price  rating  \
0               Essence Mascara Lash Princess     9.99    2.56
1               Eyeshadow Palette with Mirror    19.99    2.86
2                             Powder Canister    14.99    4.64
3                                Red Lipstick    12.99    4.36
4                             Red Nail Polish     8.99    4.32
5                         Calvin Klein CK One    49.99    4.37
6                     Chanel Coco Noir Eau De   129.99    4.26
7                                Dior J'adore    89.99    3.80
8                          Dolce Shine Eau de    69.99    3.96
9                          Gucci Bloom Eau de    79.99    2.74
10                       Annibale Colombo Bed  1899.99    4.77
11                      Annibale Colombo Sofa  2499.99    3.92
12               Bedside Table African Cherry   299.99    2.87
13  Knoll Saarinen Executive Conference Chair   499.99    4.88
14           Wooden Bathroom Sink With Mirror   799.99    3.59
15                                      Apple     1.99    4.19
16                                 Beef Steak    12.99    4.47
17                                   Cat Food     8.99    3.13
18                               Chicken Meat     9.99    3.19
19                                Cooking Oil     4.99    4.80
20                                   Cucumber     1.49    4.07
21                                   Dog Food    10.99    4.55
22                                       Eggs     2.99    2.53
23                                 Fish Steak    14.99    3.78
24                          Green Bell Pepper     1.29    3.25
25                         Green Chili Pepper     0.99    3.66
26                                  Honey Jar     6.99    3.97
27                                  Ice Cream     5.49    3.39
28                                      Juice     3.99    3.94
29                                       Kiwi     2.49    4.93

               brand                                          thumbnail  \
0            Essence  https://cdn.dummyjson.com/product-images/beaut...
1     Glamour Beauty  https://cdn.dummyjson.com/product-images/beaut...
2       Velvet Touch  https://cdn.dummyjson.com/product-images/beaut...
3     Chic Cosmetics  https://cdn.dummyjson.com/product-images/beaut...
4       Nail Couture  https://cdn.dummyjson.com/product-images/beaut...
5       Calvin Klein  https://cdn.dummyjson.com/product-images/fragr...
6             Chanel  https://cdn.dummyjson.com/product-images/fragr...
7               Dior  https://cdn.dummyjson.com/product-images/fragr...
8    Dolce & Gabbana  https://cdn.dummyjson.com/product-images/fragr...
9              Gucci  https://cdn.dummyjson.com/product-images/fragr...
10  Annibale Colombo  https://cdn.dummyjson.com/product-images/furni...
11  Annibale Colombo  https://cdn.dummyjson.com/product-images/furni...
12     Furniture Co.  https://cdn.dummyjson.com/product-images/furni...
13             Knoll  https://cdn.dummyjson.com/product-images/furni...
14       Bath Trends  https://cdn.dummyjson.com/product-images/furni...
15               NaN  https://cdn.dummyjson.com/product-images/groce...
16               NaN  https://cdn.dummyjson.com/product-images/groce...
17               NaN  https://cdn.dummyjson.com/product-images/groce...
18               NaN  https://cdn.dummyjson.com/product-images/groce...
19               NaN  https://cdn.dummyjson.com/product-images/groce...
20               NaN  https://cdn.dummyjson.com/product-images/groce...
21               NaN  https://cdn.dummyjson.com/product-images/groce...
22               NaN  https://cdn.dummyjson.com/product-images/groce...
23               NaN  https://cdn.dummyjson.com/product-images/groce...
24               NaN  https://cdn.dummyjson.com/product-images/groce...
25               NaN  https://cdn.dummyjson.com/product-images/groce...
26               NaN  https://cdn.dummyjson.com/product-images/groce...
27               NaN  https://cdn.dummyjson.com/product-images/groce...
28               NaN  https://cdn.dummyjson.com/product-images/groce...
29               NaN  https://cdn.dummyjson.com/product-images/groce...

                                          first_image
0   https://cdn.dummyjson.com/product-images/beaut...
1   https://cdn.dummyjson.com/product-images/beaut...
2   https://cdn.dummyjson.com/product-images/beaut...
3   https://cdn.dummyjson.com/product-images/beaut...
4   https://cdn.dummyjson.com/product-images/beaut...
5   https://cdn.dummyjson.com/product-images/fragr...
6   https://cdn.dummyjson.com/product-images/fragr...
7   https://cdn.dummyjson.com/product-images/fragr...
8   https://cdn.dummyjson.com/product-images/fragr...
9   https://cdn.dummyjson.com/product-images/fragr...
10  https://cdn.dummyjson.com/product-images/furni...
11  https://cdn.dummyjson.com/product-images/furni...
12  https://cdn.dummyjson.com/product-images/furni...
13  https://cdn.dummyjson.com/product-images/furni...
14  https://cdn.dummyjson.com/product-images/furni...
15  https://cdn.dummyjson.com/product-images/groce...
16  https://cdn.dummyjson.com/product-images/groce...
17  https://cdn.dummyjson.com/product-images/groce...
18  https://cdn.dummyjson.com/product-images/groce...
19  https://cdn.dummyjson.com/product-images/groce...
20  https://cdn.dummyjson.com/product-images/groce...
21  https://cdn.dummyjson.com/product-images/groce...
22  https://cdn.dummyjson.com/product-images/groce...
23  https://cdn.dummyjson.com/product-images/groce...
24  https://cdn.dummyjson.com/product-images/groce...
25  https://cdn.dummyjson.com/product-images/groce...
26  https://cdn.dummyjson.com/product-images/groce...
27  https://cdn.dummyjson.com/product-images/groce...
28  https://cdn.dummyjson.com/product-images/groce...
29  https://cdn.dummyjson.com/product-images/groce...

In [15]:
df.head()

,title,price,rating,brand,thumbnail,first_image
0,Essence Mascara Lash Princess,9.99,2.56,Essence,https://cdn.dummyjson.com/product-images/beaut...,https://cdn.dummyjson.com/product-images/beaut...
1,Eyeshadow Palette with Mirror,19.99,2.86,Glamour Beauty,https://cdn.dummyjson.com/product-images/beaut...,https://cdn.dummyjson.com/product-images/beaut...
2,Powder Canister,14.99,4.64,Velvet Touch,https://cdn.dummyjson.com/product-images/beaut...,https://cdn.dummyjson.com/product-images/beaut...
3,Red Lipstick,12.99,4.36,Chic Cosmetics,https://cdn.dummyjson.com/product-images/beaut...,https://cdn.dummyjson.com/product-images/beaut...
4,Red Nail Polish,8.99,4.32,Nail Couture,https://cdn.dummyjson.com/product-images/beaut...,https://cdn.dummyjson.com/product-images/beaut...

In [23]:
df.tail()

,title,price,rating,brand,thumbnail,first_image
25,Green Chili Pepper,0.99,3.66,NaN,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
26,Honey Jar,6.99,3.97,NaN,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
27,Ice Cream,5.49,3.39,NaN,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
28,Juice,3.99,3.94,NaN,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
29,Kiwi,2.49,4.93,NaN,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...

In [25]:
df.shape

(30, 6)

In [27]:
df.columns

Index(['title', 'price', 'rating', 'brand', 'thumbnail', 'first_image'], dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        30 non-null     object
 1   price        30 non-null     float64
 2   rating       30 non-null     float64
 3   brand        15 non-null     object
 4   thumbnail    30 non-null     object
 5   first_image  30 non-null     object
dtypes: float64(2), object(4)
memory usage: 1.5+ KB

In [4]:
df.describe()

NameError: name 'df' is not defined

In [32]:
df["title"]

0                 Essence Mascara Lash Princess
1                 Eyeshadow Palette with Mirror
2                               Powder Canister
3                                  Red Lipstick
4                               Red Nail Polish
5                           Calvin Klein CK One
6                       Chanel Coco Noir Eau De
7                                  Dior J'adore
8                            Dolce Shine Eau de
9                            Gucci Bloom Eau de
10                         Annibale Colombo Bed
11                        Annibale Colombo Sofa
12                 Bedside Table African Cherry
13    Knoll Saarinen Executive Conference Chair
14             Wooden Bathroom Sink With Mirror
15                                        Apple
16                                   Beef Steak
17                                     Cat Food
18                                 Chicken Meat
19                                  Cooking Oil
20                                     Cucumber
21                                     Dog Food
22                                         Eggs
23                                   Fish Steak
24                            Green Bell Pepper
25                           Green Chili Pepper
26                                    Honey Jar
27                                    Ice Cream
28                                        Juice
29                                         Kiwi
Name: title, dtype: object

In [16]:
df.columns

Index(['title', 'price', 'rating', 'brand', 'thumbnail', 'first_image'], dtype='object')

In [20]:
df[df["price"]>50]

,title,price,rating,brand,thumbnail,first_image
6,Chanel Coco Noir Eau De,129.99,4.26,Chanel,https://cdn.dummyjson.com/product-images/fragr...,https://cdn.dummyjson.com/product-images/fragr...
7,Dior J'adore,89.99,3.80,Dior,https://cdn.dummyjson.com/product-images/fragr...,https://cdn.dummyjson.com/product-images/fragr...
8,Dolce Shine Eau de,69.99,3.96,Dolce & Gabbana,https://cdn.dummyjson.com/product-images/fragr...,https://cdn.dummyjson.com/product-images/fragr...
9,Gucci Bloom Eau de,79.99,2.74,Gucci,https://cdn.dummyjson.com/product-images/fragr...,https://cdn.dummyjson.com/product-images/fragr...
10,Annibale Colombo Bed,1899.99,4.77,Annibale Colombo,https://cdn.dummyjson.com/product-images/furni...,https://cdn.dummyjson.com/product-images/furni...
11,Annibale Colombo Sofa,2499.99,3.92,Annibale Colombo,https://cdn.dummyjson.com/product-images/furni...,https://cdn.dummyjson.com/product-images/furni...
12,Bedside Table African Cherry,299.99,2.87,Furniture Co.,https://cdn.dummyjson.com/product-images/furni...,https://cdn.dummyjson.com/product-images/furni...
13,Knoll Saarinen Executive Conference Chair,499.99,4.88,Knoll,https://cdn.dummyjson.com/product-images/furni...,https://cdn.dummyjson.com/product-images/furni...
14,Wooden Bathroom Sink With Mirror,799.99,3.59,Bath Trends,https://cdn.dummyjson.com/product-images/furni...,https://cdn.dummyjson.com/product-images/furni...

In [27]:
df["prices"]=df["price"]*2

In [30]:
df.columns

Index(['title', 'price', 'rating', 'brand', 'thumbnail', 'first_image'], dtype='object')

In [29]:
df.drop("prices", axis=1, inplace=True)

In [36]:
df.isnull().sum()

title          0
price          0
rating         0
brand          0
thumbnail      0
first_image    0
dtype: int64

In [33]:
df.fillna(0,inplace=True)

In [35]:
df.dropna(inplace=True)

In [42]:
df.sort_values("price",ascending=False)

,title,price,rating,brand,thumbnail,first_image
11,Annibale Colombo Sofa,19999.92,3.92,Annibale Colombo,https://cdn.dummyjson.com/product-images/furni...,https://cdn.dummyjson.com/product-images/furni...
10,Annibale Colombo Bed,15199.92,4.77,Annibale Colombo,https://cdn.dummyjson.com/product-images/furni...,https://cdn.dummyjson.com/product-images/furni...
14,Wooden Bathroom Sink With Mirror,6399.92,3.59,Bath Trends,https://cdn.dummyjson.com/product-images/furni...,https://cdn.dummyjson.com/product-images/furni...
13,Knoll Saarinen Executive Conference Chair,3999.92,4.88,Knoll,https://cdn.dummyjson.com/product-images/furni...,https://cdn.dummyjson.com/product-images/furni...
12,Bedside Table African Cherry,2399.92,2.87,Furniture Co.,https://cdn.dummyjson.com/product-images/furni...,https://cdn.dummyjson.com/product-images/furni...
6,Chanel Coco Noir Eau De,1039.92,4.26,Chanel,https://cdn.dummyjson.com/product-images/fragr...,https://cdn.dummyjson.com/product-images/fragr...
7,Dior J'adore,719.92,3.80,Dior,https://cdn.dummyjson.com/product-images/fragr...,https://cdn.dummyjson.com/product-images/fragr...
9,Gucci Bloom Eau de,639.92,2.74,Gucci,https://cdn.dummyjson.com/product-images/fragr...,https://cdn.dummyjson.com/product-images/fragr...
8,Dolce Shine Eau de,559.92,3.96,Dolce & Gabbana,https://cdn.dummyjson.com/product-images/fragr...,https://cdn.dummyjson.com/product-images/fragr...
5,Calvin Klein CK One,399.92,4.37,Calvin Klein,https://cdn.dummyjson.com/product-images/fragr...,https://cdn.dummyjson.com/product-images/fragr...
1,Eyeshadow Palette with Mirror,159.92,2.86,Glamour Beauty,https://cdn.dummyjson.com/product-images/beaut...,https://cdn.dummyjson.com/product-images/beaut...
2,Powder Canister,119.92,4.64,Velvet Touch,https://cdn.dummyjson.com/product-images/beaut...,https://cdn.dummyjson.com/product-images/beaut...
23,Fish Steak,119.92,3.78,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
3,Red Lipstick,103.92,4.36,Chic Cosmetics,https://cdn.dummyjson.com/product-images/beaut...,https://cdn.dummyjson.com/product-images/beaut...
16,Beef Steak,103.92,4.47,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
21,Dog Food,87.92,4.55,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
18,Chicken Meat,79.92,3.19,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
0,Essence Mascara Lash Princess,79.92,2.56,Essence,https://cdn.dummyjson.com/product-images/beaut...,https://cdn.dummyjson.com/product-images/beaut...
4,Red Nail Polish,71.92,4.32,Nail Couture,https://cdn.dummyjson.com/product-images/beaut...,https://cdn.dummyjson.com/product-images/beaut...
17,Cat Food,71.92,3.13,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
26,Honey Jar,55.92,3.97,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
27,Ice Cream,43.92,3.39,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
19,Cooking Oil,39.92,4.80,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
28,Juice,31.92,3.94,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
22,Eggs,23.92,2.53,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
29,Kiwi,19.92,4.93,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
15,Apple,15.92,4.19,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
20,Cucumber,11.92,4.07,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
24,Green Bell Pepper,10.32,3.25,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...
25,Green Chili Pepper,7.92,3.66,0,https://cdn.dummyjson.com/product-images/groce...,https://cdn.dummyjson.com/product-images/groce...

# __________________________________________

In [ ]:
import pandas as pd
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Asha", "Ritu", "Pooja"]
})
df2 = pd.DataFrame({
    "ID":[1,3,4],
    "Marks":[79,45,76]
})
result=pd.merge(df1,df2,on="ID",how="inner")
print(result)

In [46]:
pd.concat([df1,df2])

   ID   Name  Marks
0   1   Asha    NaN
1   2   Ritu    NaN
2   3  Pooja    NaN
0   1    NaN   79.0
1   3    NaN   45.0
2   4    NaN   76.0

In [ ]:
df.replace(columns={"name":"Firstname"})

In [ ]:
import pandas as pd
df=pd.read_csv('product.csv')
print(pf.to_string())

In [6]:
import pandas as pd

df = pd.read_csv('products.csv')

print(df.to_string())

                                        title    price  rating             brand                                                                                                    thumbnail                                                                                          first_image
0               Essence Mascara Lash Princess     9.99    2.56           Essence                 https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp                 https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp
1               Eyeshadow Palette with Mirror    19.99    2.86    Glamour Beauty                 https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp                 https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp
2                             Powder Canister    14.99    4.64      Velvet Touch                               https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp                               https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp
3                                Red Lipstick    12.99    4.36    Chic Cosmetics                                  https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp                                  https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp
4                             Red Nail Polish     8.99    4.32      Nail Couture                               https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp                               https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp
5                         Calvin Klein CK One    49.99    4.37      Calvin Klein                       https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp                       https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp
6                     Chanel Coco Noir Eau De   129.99    4.26            Chanel                   https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp                   https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp
7                                Dior J'adore    89.99    3.80              Dior                              https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp                              https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp
8                          Dolce Shine Eau de    69.99    3.96   Dolce & Gabbana                        https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp                        https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp
9                          Gucci Bloom Eau de    79.99    2.74             Gucci                        https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp                        https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp
10                       Annibale Colombo Bed  1899.99    4.77  Annibale Colombo                       https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp                       https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp
11                      Annibale Colombo Sofa  2499.99    3.92  Annibale Colombo                      https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp                      https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp
12               Bedside Table African Cherry   299.99    2.87     Furniture Co.               https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp               https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp
13  Knoll Saarinen Executive Conference Chair   499.99    4.88             Knoll  https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp  https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp
14           Wooden Bathroom Sink With Mirror   799.99    3.59       Bath Trends           https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp           https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp
15                                      Apple     1.99    4.19               NaN                                      https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp                                      https://cdn.dummyjson.com/product-images/groceries/apple/1.webp
16                                 Beef Steak    12.99    4.47               NaN                                 https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp                                 https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp
17                                   Cat Food     8.99    3.13               NaN                                   https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp                                   https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp
18                               Chicken Meat     9.99    3.19               NaN                               https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp                               https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp
19                                Cooking Oil     4.99    4.80               NaN                                https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp                                https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp
20                                   Cucumber     1.49    4.07               NaN                                   https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp                                   https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp
21                                   Dog Food    10.99    4.55               NaN                                   https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp                                   https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp
22                                       Eggs     2.99    2.53               NaN                                       https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp                                       https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp
23                                 Fish Steak    14.99    3.78               NaN                                 https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp                                 https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp
24                          Green Bell Pepper     1.29    3.25               NaN                          https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp                          https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp
25                         Green Chili Pepper     0.99    3.66               NaN                         https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp                         https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp
26                                  Honey Jar     6.99    3.97               NaN                                  https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp                                  https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp
27                                  Ice Cream     5.49    3.39               NaN                                  https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp                                  https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp
28                                      Juice     3.99    3.94               NaN                                      https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp                                      https://cdn.dummyjson.com/product-images/groceries/juice/1.webp
29                                       Kiwi     2.49    4.93               NaN                                       https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp                                       https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp

# 04/12/2025

In [4]:
import pandas as pd
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
s=pd.DataFrame({"name":["Aman","Raj"],
               "age":[1,2]})
print(s)

   name  age
0  Aman    1
1   Raj    2

In [8]:
s=pd.Series([1,2,3],index=["A","B","C"])
print(s)

A    1
B    2
C    3
dtype: int64

In [26]:
s=pd.Series({"name":"Aman","b":"Raj"})
print(s)
print(s.loc["b"])

name    Aman
b        Raj
dtype: object
Raj

In [20]:
s=pd.Series([10,20,30])
print(s.iloc[2])

30

In [29]:
s=pd.Series([10,20,30])
s[1:2]
print(s)

0    10
1    20
2    30
dtype: int64

In [33]:
s=pd.Series([10,20,30,40,50,60,70])
res=s[(s>20) & (s<50)]
print(res)

2    30
3    40
dtype: int64

In [39]:
s=pd.Series([1,2,3,4,5,6])
print(s==2)

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [50]:
s=pd.Series([10,56,20,30,40,50])
print(s.quantile(0.25))
print(s.sort_values())

22.5
0    10
2    20
3    30
4    40
5    50
1    56
dtype: int64

In [69]:
s=pd.Series([10, None, 30, None, 50])
s=s.fillna(0)
print(s)

0    10.0
1     0.0
2    30.0
3     0.0
4    50.0
dtype: float64

In [77]:
s=pd.Series([1,2,3,8,4,5,6,7])
s.where(s > 5)
print(s)

0    1
1    2
2    3
3    8
4    4
5    5
6    6
7    7
dtype: int64

In [79]:
s=pd.Series([1,2,3,4,5,6,7,8,9])
s=s.apply(lambda x:x*10)
print(s)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64

In [ ]:
import pandas as pd
data = {
    "Name": ["A", "B", "C"],
    "Age": [25, 30, 22],
    "City": ["Delhi", "Mumbai", "Pune"]
}
df = pd.DataFrame(data)
print(df)

In [80]:
d={
    "a":["A","b"],
    "b":[1,2]
}
df=pd.DataFrame(d)
print(df)

   a  b
0  A  1
1  b  2

In [83]:
df.head()
df.tail()
df.describe()

              b
count  2.000000
mean   1.500000
std    0.707107
min    1.000000
25%    1.250000
50%    1.500000
75%    1.750000
max    2.000000

In [93]:
import pandas as pd
s=pd.Series([10,20,30,40],index=['a','b','a','c'])
print(s.loc['a'])

a    10
a    30
dtype: int64

In [96]:
s.index.is_unique

False

In [102]:
s = pd.Series([10, 20, 30], index=["a", "b", "c"])
df = s.reset_index(drop=True)
print(df)

0    10
1    20
2    30
dtype: int64

In [109]:
s=pd.Series([1,2,30])
print(s+10)
print(s.eq(2))
print(s.isin([2]
            ))

0    11
1    12
2    40
dtype: int64
0    False
1     True
2    False
dtype: bool
0    False
1     True
2    False
dtype: bool

In [117]:
s=pd.Series([1,2,6,4,7])
print(s.sort_values(ascending=False))

4    7
2    6
3    4
1    2
0    1
dtype: int64

In [118]:
s = pd.Series([10, None, 20, pd.NA])
print(s.isna())
print(s.notna())
pr

0    False
1     True
2    False
3     True
dtype: bool
0     True
1    False
2     True
3    False
dtype: bool

In [123]:
s = pd.Series([10, None, 20, pd.NA])
s.dropna()
s=s.fillna(1)
print(s)

0    10
1     1
2    20
3     1
dtype: int64

C:\Users\taniya panwar\AppData\Local\Temp\ipykernel_19584\4003006711.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s=s.fillna(1)

In [127]:
s=pd.Series([10,20,30])
s=s.where(s>20,0)
print(s)

0     0
1     0
2    30
dtype: int64

In [130]:
s=pd.Series([10,20,30,40])
s=s.where(s > 10).where(s < 40)
print(s)

0     NaN
1    20.0
2    30.0
3     NaN
dtype: float64

In [131]:
s=pd.DataFrame([
    ['A',20]
    ,
    ['B',30]
],columns=['name','Age'])

print(s)

  name  Age
0    A   20
1    B   30

In [137]:
import pandas as pd
s=pd.DataFrame({
    "Name":pd.Series(["1","2","3"]),
    "AGe":pd.Series(["2233","22","33"]),
})
print(s)

  Name   AGe
0    1  2233
1    2    22
2    3    33

In [149]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Age": [25, 30, 22, 28],
    "City": ["Delhi", "Mumbai", "Pune", "Kolkata"]
})
df2 = df.set_index("Name")
df2.loc['B']
df2.loc["C","City"]

'Pune'

In [163]:
df = pd.DataFrame({
    "Name": ["A", "B", "C", "A"],
    "Age": [25, 30, 22, 28],
    "City": ["Delhi", "Mumbai", "Pune", "Kolkata"]
})
df[["Age","City"]]
df[1:3]
df2=df.set_index("Name")
df2.loc["A"]
df2.index.is_unique
df_reset=df2.reset_index()
print(df.index)

RangeIndex(start=0, stop=4, step=1)

In [3]:
import pandas as pd
d={
    "name":["a","b"],
    "age":[10,20],
}
print(pd.DataFrame(d))

  name  age
0    a   10
1    b   20

In [11]:
d=[
    ["a","b"],
    [1,2]
]
print(pd.DataFrame(d,columns=['Name','age']))

  Name age
0    a   b
1    1   2

In [14]:
s=pd.DataFrame([
    ['A',20]
    ,
    ['B',30]
    
],columns=['name','Age'])
print(s)

  name  Age
0    A   20
1    B   30

In [17]:
d={
    "name":pd.Series(["ram","shyam"]),
    "Age":pd.Series([10,20])
}
print(pd.DataFrame(d))

    name  Age
0    ram   10
1  shyam   20

In [ ]:
pd.read_csv("hellow.csv")
j=pd.json("hellow.json")

In [25]:
data={
    "name":["A","B","C"],
    "Age":[1,2,3]
}
df=pd.DataFrame(data)
print(df)
#print(df.info)
print(df.describe)

  name  Age
0    A    1
1    B    2
2    C    3
<bound method NDFrame.describe of   name  Age
0    A    1
1    B    2
2    C    3>

In [32]:
data = {
    'Name': ['Nitesh', 'Rohan', 'Amit'],
    'Age': [20, 22, 21],
    'Marks': [85, 90, 88]
}
df=pd.DataFrame(data)

0    Nitesh
1     Rohan
2      Amit
Name: Name, dtype: object

In [34]:
print(df)
df['Name']
df.Name
df[['Name','Age']]

     Name  Age  Marks
0  Nitesh   20     85
1   Rohan   22     90
2    Amit   21     88

     Name  Age
0  Nitesh   20
1   Rohan   22
2    Amit   21

In [37]:
df.iloc[2]
df.iloc[1:2]

    Name  Age  Marks
1  Rohan   22     90

In [43]:
#Custome Object
df2=df.set_index("Name")
df2.loc["Nitesh"]

Age      20
Marks    85
Name: Nitesh, dtype: int64

In [44]:
df.set_index('Name', inplace=True)
df.loc['Nitesh']

Age      20
Marks    85
Name: Nitesh, dtype: int64

In [45]:
df.loc[:, 'Name':'Marks']

Empty DataFrame
Columns: []
Index: [Nitesh, Rohan, Amit]

In [48]:
df[df['Age']>20]

       Age  Marks
Name
Rohan   22     90
Amit    21     88

In [50]:
df[(df['Age']>20) & (df['Marks']>80)]

       Age  Marks
Name
Rohan   22     90
Amit    21     88

In [82]:
print(df)
df['Name']
df.Name

   index  Age  Marks
0      0   20     85
1      1   22     90
2      2   21     88

KeyError: 'Name'

In [75]:
df = df.reset_index(drop=True)
print(df.index)
print(df.index
     )

RangeIndex(start=0, stop=3, step=1)
RangeIndex(start=0, stop=3, step=1)

In [78]:
df2 = df2.reset_index()   # drop=True mat likho
print(df2)
print(df2.index)
print(df2.columns)

   index  Age  Marks
0      0   20     85
1      1   22     90
2      2   21     88
RangeIndex(start=0, stop=3, step=1)
Index(['index', 'Age', 'Marks'], dtype='object')

In [81]:
df = df.reset_index()   # drop=True mat likho
print(df)
print(df.index)
print(df.columns)

   index  Age  Marks
0      0   20     85
1      1   22     90
2      2   21     88
RangeIndex(start=0, stop=3, step=1)
Index(['index', 'Age', 'Marks'], dtype='object')

In [89]:
names = ["Nitesh", "Rohan", "Amit"]
df['Name'] = names
df = df[['Name', 'Age', 'Marks']]
print(df)

     Name  Age  Marks
0  Nitesh   20     85
1   Rohan   22     90
2    Amit   21     88

In [90]:
df['Name']

0    Nitesh
1     Rohan
2      Amit
Name: Name, dtype: object

In [94]:
df.isna()
df.isna().sum()
df.isnull().sum()

Name     0
Age      0
Marks    0
dtype: int64

In [95]:
df.dropna()  # Remove rows with any NaN

     Name  Age  Marks
0  Nitesh   20     85
1   Rohan   22     90
2    Amit   21     88

In [98]:
df.dropna(subset=["Age"])

     Name  Age  Marks
0  Nitesh   20     85
1   Rohan   22     90
2    Amit   21     88

In [99]:
#Columns remove karna jisme bohot missing hai
df.dropna(axis=1)

     Name  Age  Marks
0  Nitesh   20     85
1   Rohan   22     90
2    Amit   21     88

In [101]:
df['Age'].fillna(0,inplace=True)

C:\Users\taniya panwar\AppData\Local\Temp\ipykernel_11372\3256758531.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(0,inplace=True)

In [102]:
df['Age'].fillna(df["Age"].mean(),inplace=True)

C:\Users\taniya panwar\AppData\Local\Temp\ipykernel_11372\2703313926.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df["Age"].mean(),inplace=True)

In [103]:
df.fillna(method='ffill', inplace=True)

C:\Users\taniya panwar\AppData\Local\Temp\ipykernel_11372\3970806690.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [105]:
import numpy as np
df['Age']=df['Age'].replace(['??','#NA','-'],np.nan)

In [106]:
df.dtypes

Name     object
Age       int64
Marks     int64
dtype: object

In [110]:
## Converting
df['Marks']=pd.to_numeric(df['Marks'], errors='coerce')
df['Age']=df['Age'].astype(int)

In [113]:
df.duplicated()
df.duplicated().sum()

np.int64(0)

In [118]:
df[df.duplicated()]
df=df.drop_duplicates()
df=df.drop_duplicates(keep='last')

In [119]:
df = df.drop_duplicates(keep='last', ignore_index=True)

In [123]:
df['Name']=df['Name'].str.lower()
df['Name']=df['Name'].str.strip()
df[df['Name'].str.contains('nit',case=False)]

NameError: name 'Fasle' is not defined

In [ ]:
df['Name'] = df['Name'].str.replace('[^A-Za-z ]', '', regex=True)
df['Initial'] = df['Name'].str.extract(r'(^\w)')

In [124]:
df['Name']=df['Name'].str.lower()
print(df['Name'])

0    nitesh
1     rohan
2      amit
Name: Name, dtype: object

# Phase 5

In [126]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Nitesh', 'Rohan', 'Amit', 'Priya', 'Simran', 'Kunal'],
    'Age': [20, 22, 21, 23, 22, 24],
    'Gender': ['M', 'M', 'M', 'F', 'F', 'M'],
    'Maths': [85, 90, 88, 92, 70, 60],
    'Science': [80, 89, 85, 95, 68, 75],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Delhi', 'Mumbai'],
    'Marks': [85, 90, 88, 93, 72, 68],
    'Date_of_Joining': ['2020-01-10', '2019-05-12', '2021-03-09', '2018-12-01', '2020-08-15', '2019-11-20']
})

df

     Name  Age Gender  Maths  Science     City  Marks Date_of_Joining
0  Nitesh   20      M     85       80    Delhi     85      2020-01-10
1   Rohan   22      M     90       89   Mumbai     90      2019-05-12
2    Amit   21      M     88       85    Delhi     88      2021-03-09
3   Priya   23      F     92       95  Chennai     93      2018-12-01
4  Simran   22      F     70       68    Delhi     72      2020-08-15
5   Kunal   24      M     60       75   Mumbai     68      2019-11-20

In [134]:
df['Total']=df['Maths']+df['Science']
df['doubleMarks']=df['Marks']*2
df['pass']=df['Marks']>40
df

,Name,Age,Gender,Maths,Science,City,Marks,Date_of_Joining,Total,doubleMarks,pass
0,Nitesh,20,M,85,80,Delhi,85,2020-01-10,165,170,True
1,Rohan,22,M,90,89,Mumbai,90,2019-05-12,179,180,True
2,Amit,21,M,88,85,Delhi,88,2021-03-09,173,176,True
3,Priya,23,F,92,95,Chennai,93,2018-12-01,187,186,True
4,Simran,22,F,70,68,Delhi,72,2020-08-15,138,144,True
5,Kunal,24,M,60,75,Mumbai,68,2019-11-20,135,136,True

In [139]:
import numpy as np

conditions = [
    df['Marks'] >= 90,
    df['Marks'] >= 75,
    df['Marks'] >= 50,
    df['Marks'] < 50
]

values = ['A', 'B', 'C', 'F']

df['Grade'] = np.select(conditions, values)

TypeError: Choicelist and default value do not have a common dtype: The DType <class 'numpy.dtypes._PyLongDType'> could not be promoted by <class 'numpy.dtypes.StrDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyLongDType'>)

In [142]:
gender_map={'M':"Male",'F':'Female'}
df['GenderFull']=df['Gender'].map(gender_map)
df

,Name,Age,Gender,Maths,Science,City,Marks,Date_of_Joining,Total,doubleMarks,pass,GenderFull
0,Nitesh,20,M,85,80,Delhi,85,2020-01-10,165,170,True,Male
1,Rohan,22,M,90,89,Mumbai,90,2019-05-12,179,180,True,Male
2,Amit,21,M,88,85,Delhi,88,2021-03-09,173,176,True,Male
3,Priya,23,F,92,95,Chennai,93,2018-12-01,187,186,True,Female
4,Simran,22,F,70,68,Delhi,72,2020-08-15,138,144,True,Female
5,Kunal,24,M,60,75,Mumbai,68,2019-11-20,135,136,True,Male

In [144]:
#.assign() → Multiple new columns in one line
df=df.assign(
    Total = df['Maths'] + df['Science'],
    Avg = lambda x: x['Total'] / 2
)

In [145]:
df

,Name,Age,Gender,Maths,Science,City,Marks,Date_of_Joining,Total,doubleMarks,pass,GenderFull,Avg
0,Nitesh,20,M,85,80,Delhi,85,2020-01-10,165,170,True,Male,82.5
1,Rohan,22,M,90,89,Mumbai,90,2019-05-12,179,180,True,Male,89.5
2,Amit,21,M,88,85,Delhi,88,2021-03-09,173,176,True,Male,86.5
3,Priya,23,F,92,95,Chennai,93,2018-12-01,187,186,True,Female,93.5
4,Simran,22,F,70,68,Delhi,72,2020-08-15,138,144,True,Female,69.0
5,Kunal,24,M,60,75,Mumbai,68,2019-11-20,135,136,True,Male,67.5

In [146]:
df=df.astype(
    {
        'Age': 'int32',
    'Marks': 'float32',
    'Gender': 'category'
    }
)

In [148]:
df['City'] = df['City'].astype('category')

In [149]:
df['Age']=pd.to_numeric(df['Age'],downcast='integer')

In [152]:
df['Maths']=pd.to_numeric(df['Maths'],downcast='float')
df

,Name,Age,Gender,Maths,Science,City,Marks,Date_of_Joining,Total,doubleMarks,pass,GenderFull,Avg
0,Nitesh,20,M,85.0,80,Delhi,85.0,2020-01-10,165,170,True,Male,82.5
1,Rohan,22,M,90.0,89,Mumbai,90.0,2019-05-12,179,180,True,Male,89.5
2,Amit,21,M,88.0,85,Delhi,88.0,2021-03-09,173,176,True,Male,86.5
3,Priya,23,F,92.0,95,Chennai,93.0,2018-12-01,187,186,True,Female,93.5
4,Simran,22,F,70.0,68,Delhi,72.0,2020-08-15,138,144,True,Female,69.0
5,Kunal,24,M,60.0,75,Mumbai,68.0,2019-11-20,135,136,True,Male,67.5

In [153]:
df = df.drop(columns=['Unnamed: 0', 'level_0'])

KeyError: "['Unnamed: 0', 'level_0'] not found in axis"

# Phase 6

In [156]:
df_sorted = df.sort_values(by='Marks', ascending=True)
print(df_sorted)

     Name  Age Gender  Maths  Science     City  Marks Date_of_Joining  Total  \
5   Kunal   24      M   60.0       75   Mumbai   68.0      2019-11-20    135
4  Simran   22      F   70.0       68    Delhi   72.0      2020-08-15    138
0  Nitesh   20      M   85.0       80    Delhi   85.0      2020-01-10    165
2    Amit   21      M   88.0       85    Delhi   88.0      2021-03-09    173
1   Rohan   22      M   90.0       89   Mumbai   90.0      2019-05-12    179
3   Priya   23      F   92.0       95  Chennai   93.0      2018-12-01    187

   doubleMarks  pass GenderFull   Avg
5          136  True       Male  67.5
4          144  True     Female  69.0
0          170  True       Male  82.5
2          176  True       Male  86.5
1          180  True       Male  89.5
3          186  True     Female  93.5

In [160]:
df_sorted=df.sort_values(by=['Marks','Age'],ascending=[True,False])

df_sorted_index = df.sort_index()

In [165]:
# Marks > 85 wale rows
df.query('Marks>80')
df.query('Marks>23 & Marks<80')

,Name,Age,Gender,Maths,Science,City,Marks,Date_of_Joining,Total,doubleMarks,pass,GenderFull,Avg
4,Simran,22,F,70.0,68,Delhi,72.0,2020-08-15,138,144,True,Female,69.0
5,Kunal,24,M,60.0,75,Mumbai,68.0,2019-11-20,135,136,True,Male,67.5

In [166]:
min_age = 22
min_marks = 85
df.query('Age >= @min_age & Marks >= @min_marks')
 #python m @ k through query use hota h

,Name,Age,Gender,Maths,Science,City,Marks,Date_of_Joining,Total,doubleMarks,pass,GenderFull,Avg
1,Rohan,22,M,90.0,89,Mumbai,90.0,2019-05-12,179,180,True,Male,89.5
3,Priya,23,F,92.0,95,Chennai,93.0,2018-12-01,187,186,True,Female,93.5

In [171]:
df.query("City == 'Delhi'")
df.query("City=='Mumbai'")

,Name,Age,Gender,Maths,Science,City,Marks,Date_of_Joining,Total,doubleMarks,pass,GenderFull,Avg
1,Rohan,22,M,90.0,89,Mumbai,90.0,2019-05-12,179,180,True,Male,89.5
5,Kunal,24,M,60.0,75,Mumbai,68.0,2019-11-20,135,136,True,Male,67.5

# Phase 7

In [2]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Nitesh', 'Rohan', 'Amit', 'Priya', 'Simran', 'Kunal'],
    'Age': [20, 22, 21, 23, 22, 24],
    'Gender': ['M', 'M', 'M', 'F', 'F', 'M'],
    'Maths': [85, 90, 88, 92, 70, 60],
    'Science': [80, 89, 85, 95, 68, 75],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Delhi', 'Mumbai'],
    'Marks': [85, 90, 88, 93, 72, 68]
})

In [6]:
df

     Name  Age Gender  Maths  Science     City  Marks
0  Nitesh   20      M     85       80    Delhi     85
1   Rohan   22      M     90       89   Mumbai     90
2    Amit   21      M     88       85    Delhi     88
3   Priya   23      F     92       95  Chennai     93
4  Simran   22      F     70       68    Delhi     72
5   Kunal   24      M     60       75   Mumbai     68

# GroupBy Basics

In [175]:
## City-wise total Marks
df.groupby('City')['Marks'].sum()

City
Chennai     93
Delhi      245
Mumbai     158
Name: Marks, dtype: int64

In [176]:
df.groupby('City',as_index=False)['Marks'].sum()

      City  Marks
0  Chennai     93
1    Delhi    245
2   Mumbai    158

In [178]:
    df.groupby(['City','Gender'])['Marks'].mean()

City     Gender
Chennai  F         93.0
Delhi    F         72.0
         M         86.5
Mumbai   M         79.0
Name: Marks, dtype: float64

In [179]:
grouped = df.groupby(['City','Gender'])['Marks'].sum()
print(grouped)

City     Gender
Chennai  F          93
Delhi    F          72
         M         173
Mumbai   M         158
Name: Marks, dtype: int64

In [180]:
grouped.reset_index()

      City Gender  Marks
0  Chennai      F     93
1    Delhi      F     72
2    Delhi      M    173
3   Mumbai      M    158

grouped_swapped = grouped.swaplevel()
grouped_swapped

In [186]:
grouped_swapped = grouped.swaplevel()
grouped_swapped.sort_index()

Gender  City
F       Chennai     93
        Delhi       72
M       Delhi      173
        Mumbai     158
Name: Marks, dtype: int64

In [188]:
df.groupby('City')['Marks'].sum()
df.groupby('City')['Marks'].agg(['sum','mean'])

         sum       mean
City
Chennai   93  93.000000
Delhi    245  81.666667
Mumbai   158  79.000000

In [189]:
df.groupby('City').agg({
    'Marks':'sum',
    'Maths':'mean',
    'Science':'mean'
})

         Marks  Maths    Science
City
Chennai     93   92.0  95.000000
Delhi      245   81.0  77.666667
Mumbai     158   75.0  82.000000

In [192]:
df.groupby('City').agg(
    TotalMarks=('Marks','sum'),
    AvgMaths=('Maths','mean'),
    AvgScience=('Science','mean')
)

         TotalMarks  AvgMaths  AvgScience
City
Chennai          93      92.0   95.000000
Delhi           245      81.0   77.666667
Mumbai          158      75.0   82.000000

In [8]:
df['City_Mean_Marks'] = df.groupby('City')['Marks'].transform('mean')

In [11]:
df['City_Mean_Marks']=df.groupby('City')['Marks'].sum()
print(df['City_Mean_Marks'])

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: City_Mean_Marks, dtype: float64

# P8

In [12]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Delhi','Delhi','Mumbai','Mumbai','Delhi'],
    'Product': ['A','B','A','B','A'],
    'Sales': [100,150,200,300,120]
})
print(df)

     City Product  Sales
0   Delhi       A    100
1   Delhi       B    150
2  Mumbai       A    200
3  Mumbai       B    300
4   Delhi       A    120

In [ ]:
import numpy as np
help.genfromtxt()