# Phase 9
# MERGING & JOINING DATA

In [6]:
import pandas as pd

df1 = pd.DataFrame({
    'id':[1,2],
    'city':['Delhi','Mumbai']
})

df2 = pd.DataFrame({
    'id':[3,4],
    'city':['Pune','Jaipur']
})
pd.concat([df1,df2],ignore_index=True)

   id    city
0   1   Delhi
1   2  Mumbai
2   3    Pune
3   4  Jaipur

In [7]:
df1 = pd.DataFrame({'id':[1,2], 'name':['A','B']})
df2 = pd.DataFrame({'id':[3,4], 'age':[21,22]})

pd.concat([df1, df2], ignore_index=True)

   id name   age
0   1    A   NaN
1   2    B   NaN
2   3  NaN  21.0
3   4  NaN  22.0

In [10]:
df1 = pd.DataFrame({'a':[10,20]})
df2 = pd.DataFrame({'b':[100,200]})
pd.concat([df1,df2],axis=1)

    a    b
0  10  100
1  20  200

In [11]:
df1 = pd.DataFrame({'a':[10,20]}, index=[0,1])
df2 = pd.DataFrame({'b':[100,200]}, index=[1,2])
pd.concat([df1,df2],axis=1)

      a      b
0  10.0    NaN
1  20.0  100.0
2   NaN  200.0

# join

In [23]:
df1 = pd.DataFrame({
    'id':[1,2,3],
    'name':['A','B','C']
})

df2 = pd.DataFrame({
    'id':[1,2,4],
    'salary':[1000,2000,3000]
})
print(df1,df2)

   id name
0   1    A
1   2    B
2   3    C    id  salary
0   1    1000
1   2    2000
2   4    3000

In [14]:
#inner join
pd.merge(df1,df2,on="id",how="inner")

   id name  salary
0   1    A    1000
1   2    B    2000

In [15]:
df1 = pd.DataFrame({'id':[1,1,2], 'year':[2021,2022,2021], 'name':['A','A2','B']})
df2 = pd.DataFrame({'id':[1,2], 'year':[2021,2021], 'salary':[100,200]})
pd.merge(df1,df2,on=["id","year"],how="inner")

   id  year name  salary
0   1  2021    A     100
1   2  2021    B     200

In [24]:
pd.merge(df1,df2,on="id",how="left")

   id name  salary
0   1    A  1000.0
1   2    B  2000.0
2   3    C     NaN

In [19]:
df2 = pd.DataFrame({'id':[1], 'salary':[1000]})

pd.merge(df1, df2, how='left')

   id name  salary
0   1    A  1000.0
1   2    B     NaN
2   3    C     NaN

In [21]:
df1 = pd.DataFrame({
    'id':[1,2,3],
    'name':['A','B','C']
})

df2 = pd.DataFrame({
    'id':[1,2,4],
    'salary':[1000,2000,3000]
})
print(df1,df2)
df2=pd.DataFrame({'id':[2],'salary':[1000]})
print(df2)    # ynha df2 replace ho gya h isliye sirf ak hi value hogi

   id  salary
0   2    1000

In [25]:
df1 = pd.DataFrame({
    'id':[1,2,3],
    'name':['A','B','C']
})

df2 = pd.DataFrame({
    'id':[1,2,4],
    'salary':[1000,2000,3000]
})
print(df1,df2)

   id name
0   1    A
1   2    B
2   3    C    id  salary
0   1    1000
1   2    2000
2   4    3000

In [26]:
pd.merge(df1, df2, how='right', on="id")

   id name  salary
0   1    A    1000
1   2    B    2000
2   4  NaN    3000

In [29]:
pd.merge(df1,df2,how="outer",on="id")

   id name  salary
0   1    A  1000.0
1   2    B  2000.0
2   3    C     NaN
3   4  NaN  3000.0

In [32]:
df1 = pd.DataFrame({'name':['A','B','C']}, index=[1,2,3])
df2 = pd.DataFrame({'salary':[100,200]}, index=[1,2])
print(df1,df2)
df1.join(df2)

  name
1    A
2    B
3    C    salary
1     100
2     200

  name  salary
1    A   100.0
2    B   200.0
3    C     NaN

In [ ]:
df1 = pd.DataFrame({'value':[10,20]}, index=[1,2])
df2 = pd.DataFrame({'value':[100,200]}, index=[1,2])

df1.join(df2, lsuffix='_left', rsuffix='_right')


df1 = pd.DataFrame({
    'id':[1,2,3],
    'name':['A','B','C']
})

df2 = pd.DataFrame({
    'id':[1,2,4],
    'salary':[1000,2000,3000]
})
df1 = df1.set_index("id")
df2 = df2.set_index("id")

df1.join(df2,how="right")

In [46]:

df1.join(df2, lsuffix="_l")

   name  salary
id
1     A  1000.0
2     B  2000.0
3     C     NaN

In [49]:
df1 = pd.DataFrame({"id":[1,2], "name":["A","B"]})
df2 = pd.DataFrame({"id":[3,4], "name":["C","D"]})
#row_Wise_concat
pd.concat([df1,df2],ignore_index=True)

   id name
0   1    A
1   2    B
2   3    C
3   4    D

In [53]:
# Column-wise concat
# Same df1 aur df2:
# ➡ Column-wise concat karo
# But df2 me columns rename karke extra info jaisa dikhao.
pd.concat([df1,df2],axis=1)

   id name  id name
0   1    A   3    C
1   2    B   4    D

In [56]:
# Q4. concat with keys

# df1 aur df2 ko concat karo keys=["2023","2024"]
# ➡ MultiIndex kaise banta?
df1 = pd.DataFrame({"id":[1,2]})
df2 = pd.DataFrame({"id":[3,4]})
result = pd.concat([df1, df2], keys=["2023","2024"])
print(result)

        id
2023 0   1
     1   2
2024 0   3
     1   4

In [57]:
emp = pd.DataFrame({
    "id":[1,2,3,4],
    "name":["A","B","C","D"],
    "dept_id":[10,20,20,30]
})

dept = pd.DataFrame({
    "dept_id":[10,20],
    "dept_name":["HR","Finance"]
})

In [61]:
# INNER JOIN

# emp × dept
# ➡ Kaunse employees drop honge?
pd.merge(emp,dept,on="dept_id",how="inner")

   id name  dept_id dept_name
0   1    A       10        HR
1   2    B       20   Finance
2   3    C       20   Finance

In [62]:
#  LEFT JOIN

# emp × dept
# ➡ dept_name missing kahan aayega?
pd.merge(emp,dept,on="dept_id",how="left")

   id name  dept_id dept_name
0   1    A       10        HR
1   2    B       20   Finance
2   3    C       20   Finance
3   4    D       30       NaN

In [63]:
# RIGHT JOIN

# emp × dept
# ➡ right join output ka shape?
s=pd.merge(emp,dept,on="dept_id",how="right")
print(s)
# Q8. FULL OUTER JOIN
o=pd.merge(emp,dept,on="dept_id",how="outer")
print(o)
# Missing values identify karo.

   id name  dept_id dept_name
0   1    A       10        HR
1   2    B       20   Finance
2   3    C       20   Finance
   id name  dept_id dept_name
0   1    A       10        HR
1   2    B       20   Finance
2   3    C       20   Finance
3   4    D       30       NaN

In [65]:
# join on multiple columns (city,product)
dfA = pd.DataFrame({
    "city":["Delhi","Delhi","Mumbai"],
    "product":["A","B","A"],
    "sales":[10,20,30]
})

dfB = pd.DataFrame({
    "city":["Delhi","Mumbai","Mumbai"],
    "product":["A","A","B"],
    "price":[100,150,120]
})

pd.merge(dfA,dfB,on=["city","product"],how="inner")

     city product  sales  price
0   Delhi       A     10    100
1  Mumbai       A     30    150

In [72]:
# Q10. suffixes ka use

# dfA and dfB me same column hai product
# ➡ suffixes=('_left','_right') ka use karke merge karo.
#pd.merge(dfA,dfB,on="product",lsuffix='_left', rsuffix='_right',how="inner")

pd.merge(dfA, dfB, on="city", suffixes=("_left","_right"))

     city product_left  sales product_right  price
0   Delhi            A     10             A    100
1   Delhi            B     20             A    100
2  Mumbai            A     30             A    150
3  Mumbai            A     30             B    120

In [108]:
emp = pd.DataFrame({
    "id":[1,2,3,4],
    "name":["A","B","C","D"],
    "dept_id":[10,20,20,30]
})

dept = pd.DataFrame({
    "dept_id":[10,20],
    "dept_name":["HR","Finance"]
})

In [85]:
# Q11. filtered merge
# emp DataFrame se sirf dept_id=20 wale rows merge karo.
filterd=emp[emp["dept_id"]==20]
pd.merge(filterd,dept,on="dept_id",how="inner")
msg sahi se pd to  ab

   id name  dept_id dept_name
0   2    B       20   Finance
1   3    C       20   Finance

In [88]:
# Q12. merge + calculation
# Merge ke baad
# ➡ column banao sales_amount = sales * price
out = pd.merge(dfA, dfB, on=["city","product"], how="left")
out["sales_amount"] = out["sales"] * out["price"]
print(out["sales_amount"])

0    1000.0
1       NaN
2    4500.0
Name: sales_amount, dtype: float64

In [92]:
emp2=emp.set_index("dept_id")
dept2=dept.set_index("dept_id")
result=emp2.join(dept2)
print(result)

         id name dept_name
dept_id
10        1    A        HR
20        2    B   Finance
20        3    C   Finance
30        4    D       NaN

In [93]:
# Q14. join on index after setting
# Same emp & dept
# ➡ emp.set_index("dept_id").join(dept.set_index("dept_id"))
# Dept name mapping aayega ya nahi?
emp.set_index("dept_id").join(dept.set_index("dept_id"))

         id name dept_name
dept_id
10        1    A        HR
20        2    B   Finance
20        3    C   Finance
30        4    D       NaN

In [96]:
# Q15. join with suffixes

# Agar dono DataFrames me same column name ho
# ➡ join using lsuffix= & rsuffix=
result=emp.set_index("dept_id").join(dept.set_index("dept_id"),lsuffix="_empl",rsuffix="_depart")
print(result)

         id name dept_name
dept_id
10        1    A        HR
20        2    B   Finance
20        3    C   Finance
30        4    D       NaN

In [103]:

# Q16. left, right, outer in join()
# Aisi join karo:
# emp.set_index('dept_id').join(dept.set_index('dept_id'), how='outer')
# ➡ NaN kaha aayega?
print(emp)
print(dept)
emp.set_index("dept_id").join(dept.set_index("dept_id"),how="outer")

   id name  dept_id
0   1    A       10
1   2    B       20
2   3    C       20
3   4    D       30
   dept_id dept_name
0       10        HR
1       20   Finance

         id name dept_name
dept_id
10        1    A        HR
20        2    B   Finance
20        3    C   Finance
30        4    D       NaN

In [114]:
# ✅ SECTION D — ADVANCED MERGE + CONCAT MIXED
# Q17. concat + merge together
# df1 = employee info
# df2 = 2023 salary
# df3 = 2024 salary
# Step:
# 1️⃣ Row-wise concat df2 & df3
# 2️⃣ Merge with employee table
sal2023 = pd.DataFrame({"id":[1,2], "salary":[1000,1300]})
sal2024 = pd.DataFrame({"id":[1,3], "salary":[1500,1600]})
c=pd.concat([sal2023,sal2024],ignore_index=True)
pd.merge(emp,c,on="id",how="outer")

   id name  dept_id  salary
0   1    A       10  1000.0
1   1    A       10  1500.0
2   2    B       20  1300.0
3   3    C       20  1600.0
4   4    D       30     NaN

In [117]:
# Q18. merge indicator
# Use:
# pd.merge(emp, dept, on='dept_id', how='outer', indicator=True)
# ➡ Identify matched vs unmatched rows.
pd.merge(emp,dept,on='dept_id',how='outer',indicator=True)

   id name  dept_id dept_name     _merge
0   1    A       10        HR       both
1   2    B       20   Finance       both
2   3    C       20   Finance       both
3   4    D       30       NaN  left_only

In [124]:
# Q19. many-to-one join
# Add duplicate dept values:
dept2 = pd.DataFrame({
    "dept_id":[10,20,20],
    "dept_name":["HR","Finance","Fin_New"]
})

# ➡ Merge emp × dept2
# Question: rows badh jayenge kyun?
d=pd.merge(emp,dept,on="dept_id",how="outer")
print(d)
print("*****************")
d=pd.merge(emp,dept2,on="dept_id",how="outer")
print(d)

   id name  dept_id dept_name
0   1    A       10        HR
1   2    B       20   Finance
2   3    C       20   Finance
3   4    D       30       NaN
*****************
   id name  dept_id dept_name
0   1    A       10        HR
1   2    B       20   Finance
2   2    B       20   Fin_New
3   3    C       20   Finance
4   3    C       20   Fin_New
5   4    D       30       NaN

In [126]:
# Q20. many-to-many join
# Create:
A = pd.DataFrame({"x":[1,1,2]})
B = pd.DataFrame({"x":[1,1,1,2]})

# ➡ Merge A × B on x
pd.merge(A,B,on="x")
# Output rows count?

   x
0  1
1  1
2  1
3  1
4  1
5  1
6  2

In [107]:
df1 = pd.DataFrame({
    'id':[1,2,3],
    'name':['A','B','C']
})

df2 = pd.DataFrame({
    'id':[1,2,4],
    'salary':[1000,2000,3000]
})

df1.join(df2,lsuffix="_left",rsuffix="_right",how="left")

   id_left name  id_right  salary
0        1    A         1    1000
1        2    B         2    2000
2        3    C         4    3000

# DateTime

In [13]:
import pandas as pd

dates = ["2023-01-10", "2024-05-21", "2025-12-12"]
df = pd.DataFrame({"date_str": dates})
df["date"] = pd.to_datetime(df["date_str"])
print(df)

In [21]:
import pandas as pd
dates = ["2023-01-10", "2024-05-21", "2025-12-12"]
df = pd.DataFrame({"date_str": dates})
df["date"] = pd.to_datetime(df["date_str"])
print(df)
df["year"]=df["date"].dt.year
df["month"]=df["date"].dt.month
df["day"]=df["date"].dt.day
df["weekday_num"]=df["date"].dt.weekday
df["weekda_name"]=df["date"].dt.day_name()
df["week"]=df["date"].dt.isocalendar().week
#df["wee"]=df["date"].dt.week             error
print(df)

     date_str       date
0  2023-01-10 2023-01-10
1  2024-05-21 2024-05-21
2  2025-12-12 2025-12-12

AttributeError: 'DatetimeProperties' object has no attribute 'week'

In [23]:
df_2024=df[df["date"].dt.year==2024]
print(df_2024)

     date_str       date  year  month  day  weekday_num weekda_name  week
1  2024-05-21 2024-05-21  2024      5   21            1     Tuesday    21

In [26]:
df_2025=df[df["date"].dt.year==2025]
print(df_2025)

     date_str       date  year  month  day  weekday_num weekda_name  week
2  2025-12-12 2025-12-12  2025     12   12            4      Friday    50

# Resampling

In [ ]:
# Resampling
# Resampling is aggregating data over a new frequency.
# Example: daily → monthly sum or mean.
# resample('M').sum() → monthly sum.
# resample('W').mean() → weekly mean.

In [30]:
import numpy as np

# Daily sales
dates = pd.date_range(start="2025-01-01", periods=10, freq="D")
sales = [100, 150, 200, 120, 130, 160, 180, 170, 190, 200]
df_sales = pd.DataFrame({"sales": sales}, index=dates)
monthly_sales = df_sales.resample('ME').sum()
print(monthly_sales)

            sales
2025-01-31   1600

In [37]:
import pandas as pd
dates = pd.date_range(start="2025-01-01",periods=10,freq="D")
sales = [10,20,30,40,50,60,70,80,90,100]
df=pd.DataFrame({"sales":sales},index=dates)
print(df)
monthly = df.resample("ME").sum()
print(monthly)
weekly = df.resample('W').sum()
print(weekly)

            sales
2025-01-01     10
2025-01-02     20
2025-01-03     30
2025-01-04     40
2025-01-05     50
2025-01-06     60
2025-01-07     70
2025-01-08     80
2025-01-09     90
2025-01-10    100
            sales
2025-01-31    550
            sales
2025-01-05    150
2025-01-12    400

In [38]:
df2 = pd.DataFrame({
    "sales": [300, 450, 500]
}, index=pd.to_datetime(["2025-01-31","2025-02-28","2025-03-31"]))

In [39]:
upsampling = df2.resample('D').ffill()
print(upsampling)

            sales
2025-01-31    300
2025-02-01    300
2025-02-02    300
2025-02-03    300
2025-02-04    300
2025-02-05    300
2025-02-06    300
2025-02-07    300
2025-02-08    300
2025-02-09    300
2025-02-10    300
2025-02-11    300
2025-02-12    300
2025-02-13    300
2025-02-14    300
2025-02-15    300
2025-02-16    300
2025-02-17    300
2025-02-18    300
2025-02-19    300
2025-02-20    300
2025-02-21    300
2025-02-22    300
2025-02-23    300
2025-02-24    300
2025-02-25    300
2025-02-26    300
2025-02-27    300
2025-02-28    450
2025-03-01    450
2025-03-02    450
2025-03-03    450
2025-03-04    450
2025-03-05    450
2025-03-06    450
2025-03-07    450
2025-03-08    450
2025-03-09    450
2025-03-10    450
2025-03-11    450
2025-03-12    450
2025-03-13    450
2025-03-14    450
2025-03-15    450
2025-03-16    450
2025-03-17    450
2025-03-18    450
2025-03-19    450
2025-03-20    450
2025-03-21    450
2025-03-22    450
2025-03-23    450
2025-03-24    450
2025-03-25    450
2025-03-26    450
2025-03-27    450
2025-03-28    450
2025-03-29    450
2025-03-30    450
2025-03-31    500

In [44]:
df.resample('MS').agg({
    "sales":"sum",
    "sales":"mean"
})

            sales
2025-01-01   55.0

In [ ]:
# . .resample('MS') — Month START

# Useful when using billing periods.

#  .resample('W-MON') — Week starting MONDAY

# Custom weekly frequency.

In [45]:
df.groupby("store").resample('M').sum()

KeyError: 'store'

In [46]:
df["sales"].resample('D').ohlc()

            open  high  low  close
2025-01-01    10    10   10     10
2025-01-02    20    20   20     20
2025-01-03    30    30   30     30
2025-01-04    40    40   40     40
2025-01-05    50    50   50     50
2025-01-06    60    60   60     60
2025-01-07    70    70   70     70
2025-01-08    80    80   80     80
2025-01-09    90    90   90     90
2025-01-10   100   100  100    100

In [11]:
import pandas as pd

data = {
    "date": [
        "2025-01-01","2025-01-02","2025-01-03","2025-01-04","2025-01-05",
        "2025-01-06","2025-01-07","2025-01-08","2025-01-09","2025-01-10",
        "2025-01-11","2025-01-12","2025-01-13","2025-01-14","2025-01-15",
        "2025-01-16","2025-01-17","2025-01-18","2025-01-19","2025-01-20"
    ],
    "sales": [
        100,120,90,150,130,170,160,180,200,220,
        210,230,250,240,260,270,300,280,310,330
    ],
    "orders": [
        5,6,4,8,7,9,8,9,11,12,
        10,13,14,13,15,16,18,16,19,20
    ]
}

df = pd.DataFrame(data)
print(df)

df["dates"]=pd.to_datetime(df["date"])
print(df["dates"])

          date  sales  orders
0   2025-01-01    100       5
1   2025-01-02    120       6
2   2025-01-03     90       4
3   2025-01-04    150       8
4   2025-01-05    130       7
5   2025-01-06    170       9
6   2025-01-07    160       8
7   2025-01-08    180       9
8   2025-01-09    200      11
9   2025-01-10    220      12
10  2025-01-11    210      10
11  2025-01-12    230      13
12  2025-01-13    250      14
13  2025-01-14    240      13
14  2025-01-15    260      15
15  2025-01-16    270      16
16  2025-01-17    300      18
17  2025-01-18    280      16
18  2025-01-19    310      19
19  2025-01-20    330      20
0    2025-01-01
1    2025-01-02
2    2025-01-03
3    2025-01-04
4    2025-01-05
5    2025-01-06
6    2025-01-07
7    2025-01-08
8    2025-01-09
9    2025-01-10
10   2025-01-11
11   2025-01-12
12   2025-01-13
13   2025-01-14
14   2025-01-15
15   2025-01-16
16   2025-01-17
17   2025-01-18
18   2025-01-19
19   2025-01-20
Name: dates, dtype: datetime64[ns]

In [52]:
# PART A — Date Extraction
# 1.Convert date column into datetime format.
# 2.Extract:
# year
# month
# day
# weekday number
# weekday name
# 3.Filter records only for weekdays (Monday–Friday).

df["dates"]=pd.to_datetime(df["date"])
print(df["dates"])
df["year"]=df["dates"].dt.year
df["month"]=df["dates"].dt.month
df["day"]=df["dates"].dt.day
df["weekday_num"]=df["dates"].dt.weekday
df["weekday_name"]=df["dates"].dt.day_name()
print(df)

0    2025-01-01
1    2025-01-02
2    2025-01-03
3    2025-01-04
4    2025-01-05
5    2025-01-06
6    2025-01-07
7    2025-01-08
8    2025-01-09
9    2025-01-10
10   2025-01-11
11   2025-01-12
12   2025-01-13
13   2025-01-14
14   2025-01-15
15   2025-01-16
16   2025-01-17
17   2025-01-18
18   2025-01-19
19   2025-01-20
Name: dates, dtype: datetime64[ns]
          date  sales  orders      dates  year  month  day  weekday_num  \
0   2025-01-01    100       5 2025-01-01  2025      1    1            2
1   2025-01-02    120       6 2025-01-02  2025      1    2            3
2   2025-01-03     90       4 2025-01-03  2025      1    3            4
3   2025-01-04    150       8 2025-01-04  2025      1    4            5
4   2025-01-05    130       7 2025-01-05  2025      1    5            6
5   2025-01-06    170       9 2025-01-06  2025      1    6            0
6   2025-01-07    160       8 2025-01-07  2025      1    7            1
7   2025-01-08    180       9 2025-01-08  2025      1    8            2
8   2025-01-09    200      11 2025-01-09  2025      1    9            3
9   2025-01-10    220      12 2025-01-10  2025      1   10            4
10  2025-01-11    210      10 2025-01-11  2025      1   11            5
11  2025-01-12    230      13 2025-01-12  2025      1   12            6
12  2025-01-13    250      14 2025-01-13  2025      1   13            0
13  2025-01-14    240      13 2025-01-14  2025      1   14            1
14  2025-01-15    260      15 2025-01-15  2025      1   15            2
15  2025-01-16    270      16 2025-01-16  2025      1   16            3
16  2025-01-17    300      18 2025-01-17  2025      1   17            4
17  2025-01-18    280      16 2025-01-18  2025      1   18            5
18  2025-01-19    310      19 2025-01-19  2025      1   19            6
19  2025-01-20    330      20 2025-01-20  2025      1   20            0

   weekday_name
0     Wednesday
1      Thursday
2        Friday
3      Saturday
4        Sunday
5        Monday
6       Tuesday
7     Wednesday
8      Thursday
9        Friday
10     Saturday
11       Sunday
12       Monday
13      Tuesday
14    Wednesday
15     Thursday
16       Friday
17     Saturday
18       Sunday
19       Monday

In [55]:
weekdays=df[df["dates"].dt.weekday<5]
print(weekdays)

          date  sales  orders      dates  year  month  day  weekday_num  \
0   2025-01-01    100       5 2025-01-01  2025      1    1            2
1   2025-01-02    120       6 2025-01-02  2025      1    2            3
2   2025-01-03     90       4 2025-01-03  2025      1    3            4
5   2025-01-06    170       9 2025-01-06  2025      1    6            0
6   2025-01-07    160       8 2025-01-07  2025      1    7            1
7   2025-01-08    180       9 2025-01-08  2025      1    8            2
8   2025-01-09    200      11 2025-01-09  2025      1    9            3
9   2025-01-10    220      12 2025-01-10  2025      1   10            4
12  2025-01-13    250      14 2025-01-13  2025      1   13            0
13  2025-01-14    240      13 2025-01-14  2025      1   14            1
14  2025-01-15    260      15 2025-01-15  2025      1   15            2
15  2025-01-16    270      16 2025-01-16  2025      1   16            3
16  2025-01-17    300      18 2025-01-17  2025      1   17            4
19  2025-01-20    330      20 2025-01-20  2025      1   20            0

   weekday_name
0     Wednesday
1      Thursday
2        Friday
5        Monday
6       Tuesday
7     Wednesday
8      Thursday
9        Friday
12       Monday
13      Tuesday
14    Wednesday
15     Thursday
16       Friday
19       Monday

In [ ]:
# PART B — Resampling (VERY IMPORTANT)
# Daily → Weekly total sales.
# Daily → Weekly average orders.
# Daily → Monthly total sales.
# Daily → Monthly maximum sales.
# Daily → Monthly sales + orders both with agg
# sales → sum
# orders → mean

In [69]:
df["date"]=pd.to_datetime(df["date"])
df = df.set_index("date")

In [80]:
weeksales=df["sales"].resample("W").sum()
print(weeksales)
print("*******************")
week_Avg=df["orders"].resample("W").mean()
print(week_Avg)
print("*******************")
monthly_sales=df["sales"].resample("ME").sum()
print(monthly_sales)
monthly_maximum=df["sales"].resample("ME").max()

date
2025-01-05     590
2025-01-12    1370
2025-01-19    1910
2025-01-26     330
Freq: W-SUN, Name: sales, dtype: int64
*******************
date
2025-01-05     6.000000
2025-01-12    10.285714
2025-01-19    15.857143
2025-01-26    20.000000
Freq: W-SUN, Name: orders, dtype: float64
*******************
date
2025-01-31    4200
Freq: ME, Name: sales, dtype: int64

In [83]:
monthly_Agg = df.resample("ME").agg({
    "sales":"sum",
    "orders":"mean"
})
print(monthly_Agg)

            sales  orders
date
2025-01-31   4200   11.65

In [86]:
# PART C — Rolling & Expanding
# 3-day rolling mean of sales.
# 7-day rolling sum of sales.
# Expanding sum of orders.
# Expanding average of sales.
df["3_mean_rolling"]=df["sales"].rolling(3).mean()
print(df["3_mean_rolling"])
df["7_day_sum"]=df["sales"].rolling(7).sum()

date
2025-01-01           NaN
2025-01-02           NaN
2025-01-03    103.333333
2025-01-04    120.000000
2025-01-05    123.333333
2025-01-06    150.000000
2025-01-07    153.333333
2025-01-08    170.000000
2025-01-09    180.000000
2025-01-10    200.000000
2025-01-11    210.000000
2025-01-12    220.000000
2025-01-13    230.000000
2025-01-14    240.000000
2025-01-15    250.000000
2025-01-16    256.666667
2025-01-17    276.666667
2025-01-18    283.333333
2025-01-19    296.666667
2025-01-20    306.666667
Name: 3_mean_rolling, dtype: float64

In [91]:
#expanding sum of orders
df["expanding_Sum_orders"]=df["orders"].expanding().sum()
print(df["expanding_Sum_orders"])

date
2025-01-01      5.0
2025-01-02     11.0
2025-01-03     15.0
2025-01-04     23.0
2025-01-05     30.0
2025-01-06     39.0
2025-01-07     47.0
2025-01-08     56.0
2025-01-09     67.0
2025-01-10     79.0
2025-01-11     89.0
2025-01-12    102.0
2025-01-13    116.0
2025-01-14    129.0
2025-01-15    144.0
2025-01-16    160.0
2025-01-17    178.0
2025-01-18    194.0
2025-01-19    213.0
2025-01-20    233.0
Name: expanding_Sum_orders, dtype: float64

In [92]:
df["expanding_avg"]=df["sales"].expanding().mean()
print(df["expanding_avg"])

date
2025-01-01    100.000000
2025-01-02    110.000000
2025-01-03    103.333333
2025-01-04    115.000000
2025-01-05    118.000000
2025-01-06    126.666667
2025-01-07    131.428571
2025-01-08    137.500000
2025-01-09    144.444444
2025-01-10    152.000000
2025-01-11    157.272727
2025-01-12    163.333333
2025-01-13    170.000000
2025-01-14    175.000000
2025-01-15    180.666667
2025-01-16    186.250000
2025-01-17    192.941176
2025-01-18    197.777778
2025-01-19    203.684211
2025-01-20    210.000000
Name: expanding_avg, dtype: float64

In [ ]:
# PART D — Mixed Level (Interview Style)
# Identify the week with highest total sales after resampling.
# Create a new column:
#     * sales_diff = sales − previous day’s sales
# Find the date on which:
#     *sales crossed 250 for the first time
# Resample weekly and find:
#     *weekly sales growth %

In [97]:
highest_week=df["sales"].resample("W").sum().idxmax()
print(highest_week)

2025-01-19 00:00:00

In [99]:
df["sales_diff"]=df["sales"].diff()
df

,sales,orders,3_mean_rolling,7_day_sum,expanding_Sum_orders,expanding_avg,sales_diff
date,,,,,,,
2025-01-01,100,5,NaN,NaN,5.0,100.000000,NaN
2025-01-02,120,6,NaN,NaN,11.0,110.000000,20.0
2025-01-03,90,4,103.333333,NaN,15.0,103.333333,-30.0
2025-01-04,150,8,120.000000,NaN,23.0,115.000000,60.0
2025-01-05,130,7,123.333333,NaN,30.0,118.000000,-20.0
2025-01-06,170,9,150.000000,NaN,39.0,126.666667,40.0
2025-01-07,160,8,153.333333,920.0,47.0,131.428571,-10.0
2025-01-08,180,9,170.000000,1000.0,56.0,137.500000,20.0
2025-01-09,200,11,180.000000,1080.0,67.0,144.444444,20.0
2025-01-10,220,12,200.000000,1210.0,79.0,152.000000,20.0
2025-01-11,210,10,210.000000,1270.0,89.0,157.272727,-10.0
2025-01-12,230,13,220.000000,1370.0,102.0,163.333333,20.0
2025-01-13,250,14,230.000000,1450.0,116.0,170.000000,20.0
2025-01-14,240,13,240.000000,1530.0,129.0,175.000000,-10.0
2025-01-15,260,15,250.000000,1610.0,144.0,180.666667,20.0
2025-01-16,270,16,256.666667,1680.0,160.0,186.250000,10.0
2025-01-17,300,18,276.666667,1760.0,178.0,192.941176,30.0
2025-01-18,280,16,283.333333,1830.0,194.0,197.777778,-20.0
2025-01-19,310,19,296.666667,1910.0,213.0,203.684211,30.0
2025-01-20,330,20,306.666667,1990.0,233.0,210.000000,20.0

In [103]:
first_cross=df[df["sales"]>200].index[0]
print(first_cross)

2025-01-10 00:00:00

In [ ]:
#growth % = (current_week - previous_week) / previous_week * 100

In [106]:
weekly = df["sales"].resample("W").sum()
weekly_growth = weekly.pct_change() * 100
print(weekly_growth)

date
2025-01-05           NaN
2025-01-12    132.203390
2025-01-19     39.416058
2025-01-26    -82.722513
Freq: W-SUN, Name: sales, dtype: float64

In [108]:
#1️⃣7️⃣ Daily → Hourly (upsample) + forward fill
hourly=df.resample("h").ffill()
print(hourly)

                     sales  orders  3_mean_rolling  7_day_sum  \
date
2025-01-01 00:00:00    100       5             NaN        NaN
2025-01-01 01:00:00    100       5             NaN        NaN
2025-01-01 02:00:00    100       5             NaN        NaN
2025-01-01 03:00:00    100       5             NaN        NaN
2025-01-01 04:00:00    100       5             NaN        NaN
...                    ...     ...             ...        ...
2025-01-19 20:00:00    310      19      296.666667     1910.0
2025-01-19 21:00:00    310      19      296.666667     1910.0
2025-01-19 22:00:00    310      19      296.666667     1910.0
2025-01-19 23:00:00    310      19      296.666667     1910.0
2025-01-20 00:00:00    330      20      306.666667     1990.0

                     expanding_Sum_orders  expanding_avg  sales_diff
date
2025-01-01 00:00:00                   5.0     100.000000         NaN
2025-01-01 01:00:00                   5.0     100.000000         NaN
2025-01-01 02:00:00                   5.0     100.000000         NaN
2025-01-01 03:00:00                   5.0     100.000000         NaN
2025-01-01 04:00:00                   5.0     100.000000         NaN
...                                   ...            ...         ...
2025-01-19 20:00:00                 213.0     203.684211        30.0
2025-01-19 21:00:00                 213.0     203.684211        30.0
2025-01-19 22:00:00                 213.0     203.684211        30.0
2025-01-19 23:00:00                 213.0     203.684211        30.0
2025-01-20 00:00:00                 233.0     210.000000        20.0

[457 rows x 7 columns]

In [25]:
import pandas as pd

data = {
    "date": [
        "2025-01-01","2025-01-02","2025-01-03","2025-01-04","2025-01-05",
        "2025-01-06","2025-01-07","2025-01-08","2025-01-09","2025-01-10",
        "2025-01-11","2025-01-12","2025-01-13","2025-01-14","2025-01-15",
        "2025-01-16","2025-01-17","2025-01-18","2025-01-19","2025-01-20"
    ],
    "sales": [
        100,120,90,150,130,170,160,180,200,220,
        210,230,250,240,260,270,300,280,310,330
    ],
    "orders": [
        5,6,4,8,7,9,8,9,11,12,
        10,13,14,13,15,16,18,16,19,20
    ]
}

df = pd.DataFrame(data)
print(df)

# 2. Convert to datetime
df["date"] = pd.to_datetime(df["date"])

# 3. Set as index
df = df.set_index("date")

print(df)

          date  sales  orders
0   2025-01-01    100       5
1   2025-01-02    120       6
2   2025-01-03     90       4
3   2025-01-04    150       8
4   2025-01-05    130       7
5   2025-01-06    170       9
6   2025-01-07    160       8
7   2025-01-08    180       9
8   2025-01-09    200      11
9   2025-01-10    220      12
10  2025-01-11    210      10
11  2025-01-12    230      13
12  2025-01-13    250      14
13  2025-01-14    240      13
14  2025-01-15    260      15
15  2025-01-16    270      16
16  2025-01-17    300      18
17  2025-01-18    280      16
18  2025-01-19    310      19
19  2025-01-20    330      20
            sales  orders
date
2025-01-01    100       5
2025-01-02    120       6
2025-01-03     90       4
2025-01-04    150       8
2025-01-05    130       7
2025-01-06    170       9
2025-01-07    160       8
2025-01-08    180       9
2025-01-09    200      11
2025-01-10    220      12
2025-01-11    210      10
2025-01-12    230      13
2025-01-13    250      14
2025-01-14    240      13
2025-01-15    260      15
2025-01-16    270      16
2025-01-17    300      18
2025-01-18    280      16
2025-01-19    310      19
2025-01-20    330      20

In [18]:
df["sales_diff"]=df["sales"].diff()
df

          date  sales  orders      dates  sales_diff
0   2025-01-01    100       5 2025-01-01         NaN
1   2025-01-02    120       6 2025-01-02        20.0
2   2025-01-03     90       4 2025-01-03       -30.0
3   2025-01-04    150       8 2025-01-04        60.0
4   2025-01-05    130       7 2025-01-05       -20.0
5   2025-01-06    170       9 2025-01-06        40.0
6   2025-01-07    160       8 2025-01-07       -10.0
7   2025-01-08    180       9 2025-01-08        20.0
8   2025-01-09    200      11 2025-01-09        20.0
9   2025-01-10    220      12 2025-01-10        20.0
10  2025-01-11    210      10 2025-01-11       -10.0
11  2025-01-12    230      13 2025-01-12        20.0
12  2025-01-13    250      14 2025-01-13        20.0
13  2025-01-14    240      13 2025-01-14       -10.0
14  2025-01-15    260      15 2025-01-15        20.0
15  2025-01-16    270      16 2025-01-16        10.0
16  2025-01-17    300      18 2025-01-17        30.0
17  2025-01-18    280      16 2025-01-18       -20.0
18  2025-01-19    310      19 2025-01-19        30.0
19  2025-01-20    330      20 2025-01-20        20.0

In [26]:
# hourly = df.resample("h").ffill()
# print(hourly)
monthly_Start = df.resample("MS").mean().bfill()

In [27]:
# Plot sales + rolling mean
df["sales"].plot()
df["sales"].rolling(5).mean().plot()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [29]:
weekday_Avg = df.groupby(df.index.day_name())["sales"].mean()
print(weekday_Avg)

date
Friday       203.333333
Monday       250.000000
Saturday     213.333333
Sunday       223.333333
Thursday     196.666667
Tuesday      200.000000
Wednesday    180.000000
Name: sales, dtype: float64