In [2]:
import pandas as pd

df = pd.DataFrame({
    "name": ["A", "B", "C", "D", "E", "F"],
    "age": [12, 19, 25, 45, 67, 33],
    "gender": ["Male", "Female", "Female", "Male", "Female", "Male"],
    "city": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai", "Delhi"],
    "math": [78, 90, 55, 89, 45, 70],
    "science": [88, 92, 60, 94, 50, 80],
    "english": [75, 85, 65, 93, 52, 78],
    "salary": [15000, 18000, 45000, 90000, 76000, 65000],
    "height": [1.50, 1.65, 1.70, 1.72, 1.60, 1.80],
    "weight": [45, 60, 70, 82, 55, 78],
    "join_date": ["2022-05-01", "2021/06/12", "13-07-2020", "hello", "2020-01-01", "2019/03/02"]
})
df

,name,age,gender,city,math,science,english,salary,height,weight,join_date
0,A,12,Male,Delhi,78,88,75,15000,1.50,45,2022-05-01
1,B,19,Female,Mumbai,90,92,85,18000,1.65,60,2021/06/12
2,C,25,Female,Delhi,55,60,65,45000,1.70,70,13-07-2020
3,D,45,Male,Pune,89,94,93,90000,1.72,82,hello
4,E,67,Female,Mumbai,45,50,52,76000,1.60,55,2020-01-01
5,F,33,Male,Delhi,70,80,78,65000,1.80,78,2019/03/02

In [3]:
# ⭐ A. Creating New Columns (Arithmetic + Boolean)
# 1️⃣ Total marks = math + science + english
df["Total_makrs"]=df["math"]+df["science"]+df["english"]
print(df)

  name  age  gender    city  math  science  english  salary  height  weight  \
0    A   12    Male   Delhi    78       88       75   15000    1.50      45
1    B   19  Female  Mumbai    90       92       85   18000    1.65      60
2    C   25  Female   Delhi    55       60       65   45000    1.70      70
3    D   45    Male    Pune    89       94       93   90000    1.72      82
4    E   67  Female  Mumbai    45       50       52   76000    1.60      55
5    F   33    Male   Delhi    70       80       78   65000    1.80      78

    join_date  Total_makrs
0  2022-05-01          241
1  2021/06/12          267
2  13-07-2020          180
3       hello          276
4  2020-01-01          147
5  2019/03/02          228

In [12]:
# 2️⃣ Percentage = total / 3
df["Percentage"]=df["Total_makrs"]/3
print(df["Percentage"])
print(df)

0    80.333333
1    89.000000
2    60.000000
3    92.000000
4    49.000000
5    76.000000
Name: Percentage, dtype: float64
  name  age  gender    city  math  science  english  salary  height  weight  \
0    A   12    Male   Delhi    78       88       75   15000    1.50      45
1    B   19  Female  Mumbai    90       92       85   18000    1.65      60
2    C   25  Female   Delhi    55       60       65   45000    1.70      70
3    D   45    Male    Pune    89       94       93   90000    1.72      82
4    E   67  Female  Mumbai    45       50       52   76000    1.60      55
5    F   33    Male   Delhi    70       80       78   65000    1.80      78

    join_date  Total_makrs  Percentage
0  2022-05-01          241   80.333333
1  2021/06/12          267   89.000000
2  13-07-2020          180   60.000000
3       hello          276   92.000000
4  2020-01-01          147   49.000000
5  2019/03/02          228   76.000000

In [22]:
# 3️⃣ Result column: marks >= 40 → "Pass" else "Fail"
print(df)
df["is_pass"] = df["Total_makrs"] > 55
df["result"]=df["is_pass"].map({True:"Pass",False:"Fail"})
print(df["result"])

  name  age  gender    city  math  science  english  salary  height  weight  \
0    A   12    Male   Delhi    78       88       75   15000    1.50      45
1    B   19  Female  Mumbai    90       92       85   18000    1.65      60
2    C   25  Female   Delhi    55       60       65   45000    1.70      70
3    D   45    Male    Pune    89       94       93   90000    1.72      82
4    E   67  Female  Mumbai    45       50       52   76000    1.60      55
5    F   33    Male   Delhi    70       80       78   65000    1.80      78

    join_date  Total_makrs  Percentage  is_pass result
0  2022-05-01          241   80.333333     True   Pass
1  2021/06/12          267   89.000000     True   Pass
2  13-07-2020          180   60.000000     True   Pass
3       hello          276   92.000000     True   Pass
4  2020-01-01          147   49.000000     True   Pass
5  2019/03/02          228   76.000000     True   Pass
0    Pass
1    Pass
2    Pass
3    Pass
4    Pass
5    Pass
Name: result, dtype: object

In [24]:
# 4️⃣ Adult column: age >= 18 (True/False)
df["is_age"]=df["age"]>18
print(df)

  name  age  gender    city  math  science  english  salary  height  weight  \
0    A   12    Male   Delhi    78       88       75   15000    1.50      45
1    B   19  Female  Mumbai    90       92       85   18000    1.65      60
2    C   25  Female   Delhi    55       60       65   45000    1.70      70
3    D   45    Male    Pune    89       94       93   90000    1.72      82
4    E   67  Female  Mumbai    45       50       52   76000    1.60      55
5    F   33    Male   Delhi    70       80       78   65000    1.80      78

    join_date  Total_makrs  Percentage  is_pass result  is_age
0  2022-05-01          241   80.333333     True   Pass   False
1  2021/06/12          267   89.000000     True   Pass    True
2  13-07-2020          180   60.000000     True   Pass    True
3       hello          276   92.000000     True   Pass    True
4  2020-01-01          147   49.000000     True   Pass    True
5  2019/03/02          228   76.000000     True   Pass    True

In [28]:
# 5️⃣ Discount price = price – (price * 0.10)
df["Discount_Price"]=df["salary"]-(df["salary"]*0.10)
df["10%"]=df["salary"]*0.10
print(df)

  name  age  gender    city  math  science  english  salary  height  weight  \
0    A   12    Male   Delhi    78       88       75   15000    1.50      45
1    B   19  Female  Mumbai    90       92       85   18000    1.65      60
2    C   25  Female   Delhi    55       60       65   45000    1.70      70
3    D   45    Male    Pune    89       94       93   90000    1.72      82
4    E   67  Female  Mumbai    45       50       52   76000    1.60      55
5    F   33    Male   Delhi    70       80       78   65000    1.80      78

    join_date  Total_makrs  Percentage  is_pass result  is_age  \
0  2022-05-01          241   80.333333     True   Pass   False
1  2021/06/12          267   89.000000     True   Pass    True
2  13-07-2020          180   60.000000     True   Pass    True
3       hello          276   92.000000     True   Pass    True
4  2020-01-01          147   49.000000     True   Pass    True
5  2019/03/02          228   76.000000     True   Pass    True

   Discount_Price     10%
0         13500.0  1500.0
1         16200.0  1800.0
2         40500.0  4500.0
3         81000.0  9000.0
4         68400.0  7600.0
5         58500.0  6500.0

In [29]:
# 6️⃣ BMI = weight / (height**2)
df["BMI"]=df["weight"]/df["height"]**2
print(df)

  name  age  gender    city  math  science  english  salary  height  weight  \
0    A   12    Male   Delhi    78       88       75   15000    1.50      45
1    B   19  Female  Mumbai    90       92       85   18000    1.65      60
2    C   25  Female   Delhi    55       60       65   45000    1.70      70
3    D   45    Male    Pune    89       94       93   90000    1.72      82
4    E   67  Female  Mumbai    45       50       52   76000    1.60      55
5    F   33    Male   Delhi    70       80       78   65000    1.80      78

    join_date  Total_makrs  Percentage  is_pass result  is_age  \
0  2022-05-01          241   80.333333     True   Pass   False
1  2021/06/12          267   89.000000     True   Pass    True
2  13-07-2020          180   60.000000     True   Pass    True
3       hello          276   92.000000     True   Pass    True
4  2020-01-01          147   49.000000     True   Pass    True
5  2019/03/02          228   76.000000     True   Pass    True

   Discount_Price     10%        BMI
0         13500.0  1500.0  20.000000
1         16200.0  1800.0  22.038567
2         40500.0  4500.0  24.221453
3         81000.0  9000.0  27.717685
4         68400.0  7600.0  21.484375
5         58500.0  6500.0  24.074074

In [30]:
# 7️⃣ Salary hike = salary * 1.15
Salary_hike=df["salary"]*1.15
print(Salary_hike)

0     17250.0
1     20700.0
2     51750.0
3    103500.0
4     87400.0
5     74750.0
Name: salary, dtype: float64

In [31]:
# 8️⃣ High_income = salary > 80000
High_income=df["salary"]>80000
print(High_income)

0    False
1    False
2    False
3     True
4    False
5    False
Name: salary, dtype: bool

In [35]:
# 9️⃣ expensive = price > average price (compute mean first)
means=df["salary"].mean()
df["expensive"]=df['salary']>means
print(df)

  name  age  gender    city  math  science  english  salary  height  weight  \
0    A   12    Male   Delhi    78       88       75   15000    1.50      45
1    B   19  Female  Mumbai    90       92       85   18000    1.65      60
2    C   25  Female   Delhi    55       60       65   45000    1.70      70
3    D   45    Male    Pune    89       94       93   90000    1.72      82
4    E   67  Female  Mumbai    45       50       52   76000    1.60      55
5    F   33    Male   Delhi    70       80       78   65000    1.80      78

    join_date  Total_makrs  Percentage  is_pass result  is_age  \
0  2022-05-01          241   80.333333     True   Pass   False
1  2021/06/12          267   89.000000     True   Pass    True
2  13-07-2020          180   60.000000     True   Pass    True
3       hello          276   92.000000     True   Pass    True
4  2020-01-01          147   49.000000     True   Pass    True
5  2019/03/02          228   76.000000     True   Pass    True

   Discount_Price     10%        BMI  expensive
0         13500.0  1500.0  20.000000      False
1         16200.0  1800.0  22.038567      False
2         40500.0  4500.0  24.221453      False
3         81000.0  9000.0  27.717685       True
4         68400.0  7600.0  21.484375       True
5         58500.0  6500.0  24.074074       True

In [38]:
# ⭐ B. np.select() – Multi Conditions

# 11️⃣ Grade column:
# = 90 ⇒ A
# = 75 ⇒ B
# = 50 ⇒ C
# else Fail
import numpy as np
condition=[
    df["math"]>=90,
    df["math"]>=75,
    df["math"]>=50
]
choice=["A","B","c"]
df["Grade"]=np.select(condition,choice,default="Fail")
print(df)

  name  age  gender    city  math  science  english  salary  height  weight  \
0    A   12    Male   Delhi    78       88       75   15000    1.50      45
1    B   19  Female  Mumbai    90       92       85   18000    1.65      60
2    C   25  Female   Delhi    55       60       65   45000    1.70      70
3    D   45    Male    Pune    89       94       93   90000    1.72      82
4    E   67  Female  Mumbai    45       50       52   76000    1.60      55
5    F   33    Male   Delhi    70       80       78   65000    1.80      78

   ... Total_makrs  Percentage  is_pass  result is_age  Discount_Price  \
0  ...         241   80.333333     True    Pass  False         13500.0
1  ...         267   89.000000     True    Pass   True         16200.0
2  ...         180   60.000000     True    Pass   True         40500.0
3  ...         276   92.000000     True    Pass   True         81000.0
4  ...         147   49.000000     True    Pass   True         68400.0
5  ...         228   76.000000     True    Pass   True         58500.0

      10%        BMI  expensive  Grade
0  1500.0  20.000000      False      B
1  1800.0  22.038567      False      A
2  4500.0  24.221453      False      c
3  9000.0  27.717685       True      B
4  7600.0  21.484375       True   Fail
5  6500.0  24.074074       True      c

[6 rows x 21 columns]

In [44]:
# 12️⃣ Age group:

# < 13 ⇒ Child
# < 20 ⇒ Teenager
# < 60 ⇒ Adult
# else ⇒ Senior
condition=[
    df["age"]<13,
    df["age"]<20,
    df["age"]<60
] 
choice=["Child","Teenager","Adult"]
df["Age_Group"]=np.select(condition,choice,default="Senior")
print(df)

  name  age  gender    city  math  science  english  salary  height  weight  \
0    A   12    Male   Delhi    78       88       75   15000    1.50      45
1    B   19  Female  Mumbai    90       92       85   18000    1.65      60
2    C   25  Female   Delhi    55       60       65   45000    1.70      70
3    D   45    Male    Pune    89       94       93   90000    1.72      82
4    E   67  Female  Mumbai    45       50       52   76000    1.60      55
5    F   33    Male   Delhi    70       80       78   65000    1.80      78

   ... Percentage  is_pass  result  is_age Discount_Price     10%        BMI  \
0  ...  80.333333     True    Pass   False        13500.0  1500.0  20.000000
1  ...  89.000000     True    Pass    True        16200.0  1800.0  22.038567
2  ...  60.000000     True    Pass    True        40500.0  4500.0  24.221453
3  ...  92.000000     True    Pass    True        81000.0  9000.0  27.717685
4  ...  49.000000     True    Pass    True        68400.0  7600.0  21.484375
5  ...  76.000000     True    Pass    True        58500.0  6500.0  24.074074

   expensive  Grade  Age_Group
0      False      B      Child
1      False      A   Teenager
2      False      c      Adult
3       True      B      Adult
4       True   Fail     Senior
5       True      c      Adult

[6 rows x 22 columns]

In [47]:

# 13️⃣ Salary level:
# < 20000 ⇒ Low
# < 60000 ⇒ Medium
# else ⇒ High
condition=[
    df["salary"]<20000,
    df["salary"]<60000
]
choice=["Low","Medium"]
df["salary_level"]=np.select(condition,choice,default="High")
df

,name,age,gender,city,math,science,english,salary,height,weight,...,is_pass,result,is_age,Discount_Price,10%,BMI,expensive,Grade,Age_Group,salary_level
0,A,12,Male,Delhi,78,88,75,15000,1.50,45,...,True,Pass,False,13500.0,1500.0,20.000000,False,B,Child,Low
1,B,19,Female,Mumbai,90,92,85,18000,1.65,60,...,True,Pass,True,16200.0,1800.0,22.038567,False,A,Teenager,Low
2,C,25,Female,Delhi,55,60,65,45000,1.70,70,...,True,Pass,True,40500.0,4500.0,24.221453,False,c,Adult,Medium
3,D,45,Male,Pune,89,94,93,90000,1.72,82,...,True,Pass,True,81000.0,9000.0,27.717685,True,B,Adult,High
4,E,67,Female,Mumbai,45,50,52,76000,1.60,55,...,True,Pass,True,68400.0,7600.0,21.484375,True,Fail,Senior,High
5,F,33,Male,Delhi,70,80,78,65000,1.80,78,...,True,Pass,True,58500.0,6500.0,24.074074,True,c,Adult,High

In [52]:
# ⭐ C. map() – Category Mapping

# 14️⃣ city_map = {“Delhi”: 1, “Mumbai”: 2, “Pune”: 3} → map() use karke new column banao.
city_map={"Delhi":1,"Mumbai":2,"Pune":3}
df["City_category"]=df["city"].map(city_map)
df

,name,age,gender,city,math,science,english,salary,height,weight,...,result,is_age,Discount_Price,10%,BMI,expensive,Grade,Age_Group,salary_level,City_category
0,A,12,Male,Delhi,78,88,75,15000,1.50,45,...,Pass,False,13500.0,1500.0,20.000000,False,B,Child,Low,1
1,B,19,Female,Mumbai,90,92,85,18000,1.65,60,...,Pass,True,16200.0,1800.0,22.038567,False,A,Teenager,Low,2
2,C,25,Female,Delhi,55,60,65,45000,1.70,70,...,Pass,True,40500.0,4500.0,24.221453,False,c,Adult,Medium,1
3,D,45,Male,Pune,89,94,93,90000,1.72,82,...,Pass,True,81000.0,9000.0,27.717685,True,B,Adult,High,3
4,E,67,Female,Mumbai,45,50,52,76000,1.60,55,...,Pass,True,68400.0,7600.0,21.484375,True,Fail,Senior,High,2
5,F,33,Male,Delhi,70,80,78,65000,1.80,78,...,Pass,True,58500.0,6500.0,24.074074,True,c,Adult,High,1

In [54]:
# 15️⃣ gender_map = {"Male": 0, "Female": 1}
gender_map={"Male" :0,"Female":1}
df["gender_map"]=df["gender"].map(gender_map)
df

,name,age,gender,city,math,science,english,salary,height,weight,...,is_age,Discount_Price,10%,BMI,expensive,Grade,Age_Group,salary_level,City_category,gender_map
0,A,12,Male,Delhi,78,88,75,15000,1.50,45,...,False,13500.0,1500.0,20.000000,False,B,Child,Low,1,0
1,B,19,Female,Mumbai,90,92,85,18000,1.65,60,...,True,16200.0,1800.0,22.038567,False,A,Teenager,Low,2,1
2,C,25,Female,Delhi,55,60,65,45000,1.70,70,...,True,40500.0,4500.0,24.221453,False,c,Adult,Medium,1,1
3,D,45,Male,Pune,89,94,93,90000,1.72,82,...,True,81000.0,9000.0,27.717685,True,B,Adult,High,3,0
4,E,67,Female,Mumbai,45,50,52,76000,1.60,55,...,True,68400.0,7600.0,21.484375,True,Fail,Senior,High,2,1
5,F,33,Male,Delhi,70,80,78,65000,1.80,78,...,True,58500.0,6500.0,24.074074,True,c,Adult,High,1,0

In [65]:
# 16️⃣Drop Columns
df.drop(columns=["Percentage"], inplace=True)
df

,name,age,gender,city,math,science,english,salary,height,weight,join_date,is_pass,result,is_age,Discount_Price,Grade,Age_Group,salary_level,City_category,gender_map
0,A,12,Male,Delhi,78,88,75,15000,1.50,45,2022-05-01,True,Pass,False,13500.0,B,Child,Low,1,0
1,B,19,Female,Mumbai,90,92,85,18000,1.65,60,2021/06/12,True,Pass,True,16200.0,A,Teenager,Low,2,1
2,C,25,Female,Delhi,55,60,65,45000,1.70,70,13-07-2020,True,Pass,True,40500.0,c,Adult,Medium,1,1
3,D,45,Male,Pune,89,94,93,90000,1.72,82,hello,True,Pass,True,81000.0,B,Adult,High,3,0
4,E,67,Female,Mumbai,45,50,52,76000,1.60,55,2020-01-01,True,Pass,True,68400.0,Fail,Senior,High,2,1
5,F,33,Male,Delhi,70,80,78,65000,1.80,78,2019/03/02,True,Pass,True,58500.0,c,Adult,High,1,0

In [67]:
# ⭐ D. assign() – Multiple Columns Together
# 17️⃣ total & percentage ek saath assign() se banao
df.assign(
    total=df["math"]+df["science"]+df["english"],
    percentage= lambda x: x["total"] / 3
)

,name,age,gender,city,math,science,english,salary,height,weight,...,result,is_age,Discount_Price,Grade,Age_Group,salary_level,City_category,gender_map,total,percentage
0,A,12,Male,Delhi,78,88,75,15000,1.50,45,...,Pass,False,13500.0,B,Child,Low,1,0,241,80.333333
1,B,19,Female,Mumbai,90,92,85,18000,1.65,60,...,Pass,True,16200.0,A,Teenager,Low,2,1,267,89.000000
2,C,25,Female,Delhi,55,60,65,45000,1.70,70,...,Pass,True,40500.0,c,Adult,Medium,1,1,180,60.000000
3,D,45,Male,Pune,89,94,93,90000,1.72,82,...,Pass,True,81000.0,B,Adult,High,3,0,276,92.000000
4,E,67,Female,Mumbai,45,50,52,76000,1.60,55,...,Pass,True,68400.0,Fail,Senior,High,2,1,147,49.000000
5,F,33,Male,Delhi,70,80,78,65000,1.80,78,...,Pass,True,58500.0,c,Adult,High,1,0,228,76.000000

In [77]:
# 18️⃣ is_pass & is_adult assign() se banao
#df.drop(columns=["is_pass"])
df.assign(
    is_pass=df["math"] > 40,
    result = lambda x:x["is_pass"].map({True:"pass",False:"Fail"})
)
df

,name,age,gender,city,math,science,english,salary,height,weight,join_date,is_pass,result,is_age,Discount_Price,Grade,Age_Group,salary_level,City_category,gender_map
0,A,12,Male,Delhi,78,88,75,15000,1.50,45,2022-05-01,True,Pass,False,13500.0,B,Child,Low,1,0
1,B,19,Female,Mumbai,90,92,85,18000,1.65,60,2021/06/12,True,Pass,True,16200.0,A,Teenager,Low,2,1
2,C,25,Female,Delhi,55,60,65,45000,1.70,70,13-07-2020,True,Pass,True,40500.0,c,Adult,Medium,1,1
3,D,45,Male,Pune,89,94,93,90000,1.72,82,hello,True,Pass,True,81000.0,B,Adult,High,3,0
4,E,67,Female,Mumbai,45,50,52,76000,1.60,55,2020-01-01,True,Pass,True,68400.0,Fail,Senior,High,2,1
5,F,33,Male,Delhi,70,80,78,65000,1.80,78,2019/03/02,True,Pass,True,58500.0,c,Adult,High,1,0

In [79]:
# 19️⃣ 3 columns ek line me banao:
# - after_tax = salary * 0.9
# - doubled_salary = salary * 2
# - yearly_salary = salary * 12
df.assign(
    after_tax=df["salary"]*0.9,
    doubled_salary=df["salary"]*2,
    yearly_salary = df["salary"]*12,
)

,name,age,gender,city,math,science,english,salary,height,weight,...,is_age,Discount_Price,Grade,Age_Group,salary_level,City_category,gender_map,after_tax,doubled_salary,yearly_salary
0,A,12,Male,Delhi,78,88,75,15000,1.50,45,...,False,13500.0,B,Child,Low,1,0,13500.0,30000,180000
1,B,19,Female,Mumbai,90,92,85,18000,1.65,60,...,True,16200.0,A,Teenager,Low,2,1,16200.0,36000,216000
2,C,25,Female,Delhi,55,60,65,45000,1.70,70,...,True,40500.0,c,Adult,Medium,1,1,40500.0,90000,540000
3,D,45,Male,Pune,89,94,93,90000,1.72,82,...,True,81000.0,B,Adult,High,3,0,81000.0,180000,1080000
4,E,67,Female,Mumbai,45,50,52,76000,1.60,55,...,True,68400.0,Fail,Senior,High,2,1,68400.0,152000,912000
5,F,33,Male,Delhi,70,80,78,65000,1.80,78,...,True,58500.0,c,Adult,High,1,0,58500.0,130000,780000

In [87]:
# ⭐ E. Dtype Conversions + Optimization
# 20️⃣ age column ko int me convert karo
df["age"]=df["age"].astype(int)
print(df["age"])

0    12
1    19
2    25
3    45
4    67
5    33
Name: age, dtype: int64

In [109]:
# 21️⃣ marks ko float me convert karo
df["math"]=df["math"].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [108]:
# 22️⃣ price ko numeric me convert karo errors='coerce'
df["salary"]=pd.to_numeric(df["salary"],errors="coerce")
df

,name,age,gender,city,math,science,english,salary,height,weight,join_date,is_pass,result,is_age,Discount_Price,Grade,Age_Group,salary_level,City_category,gender_map
0,A,12,Male,Delhi,NaN,88,75,15000,1.50,45,2022-05-01,True,Pass,False,13500.0,B,Child,Low,1,0
1,B,19,Female,Mumbai,NaN,92,85,18000,1.65,60,2021/06/12,True,Pass,True,16200.0,A,Teenager,Low,2,1
2,C,25,Female,Delhi,NaN,60,65,45000,1.70,70,13-07-2020,True,Pass,True,40500.0,c,Adult,Medium,1,1
3,D,45,Male,Pune,NaN,94,93,90000,1.72,82,hello,True,Pass,True,81000.0,B,Adult,High,3,0
4,E,67,Female,Mumbai,NaN,50,52,76000,1.60,55,2020-01-01,True,Pass,True,68400.0,Fail,Senior,High,2,1
5,F,33,Male,Delhi,NaN,80,78,65000,1.80,78,2019/03/02,True,Pass,True,58500.0,c,Adult,High,1,0

In [112]:
# 23️⃣ date ko datetime me convert karo
df["join_date"]=pd.to_datetime(df["join_date"],errors="coerce")

In [114]:
# 24️⃣ city ko category dtype me convert karo
df["city"] = df["city"].astype("category")

In [116]:
# 25️⃣ salary column ko downcast integer me convert karo
df["salary"]=pd.to_numeric(df["salary"],downcast="integer")

,name,age,gender,city,math,science,english,salary,height,weight,join_date,is_pass,result,is_age,Discount_Price,Grade,Age_Group,salary_level,City_category,gender_map
0,A,12,Male,Delhi,NaN,88,75,15000,1.50,45,2022-05-01,True,Pass,False,13500.0,B,Child,Low,1,0
1,B,19,Female,Mumbai,NaN,92,85,18000,1.65,60,NaT,True,Pass,True,16200.0,A,Teenager,Low,2,1
2,C,25,Female,Delhi,NaN,60,65,45000,1.70,70,NaT,True,Pass,True,40500.0,c,Adult,Medium,1,1
3,D,45,Male,Pune,NaN,94,93,90000,1.72,82,NaT,True,Pass,True,81000.0,B,Adult,High,3,0
4,E,67,Female,Mumbai,NaN,50,52,76000,1.60,55,2020-01-01,True,Pass,True,68400.0,Fail,Senior,High,2,1
5,F,33,Male,Delhi,NaN,80,78,65000,1.80,78,NaT,True,Pass,True,58500.0,c,Adult,High,1,0

In [13]:
# Part 1: Sorting (1–10)
# Ek DataFrame hai df:
import pandas as pd
df=pd.DataFrame({
    "name": ["A","B", "C", "D"],
    "marks" : [85, 92, 70, 92],
    "age" : [15, 16, 15, 17]
})

# Marks column ke basis pe ascending order me sort karo.
s=df.sort_values(by=["marks"],ascending=True)
print(s)

  name  marks  age
2    C     70   15
0    A     85   15
1    B     92   16
3    D     92   17

In [14]:
# Marks descending + age ascending ke basis pe sort karo.
s=df.sort_values(by=["marks","age"],ascending=[False,True])
print(s)

  name  marks  age
1    B     92   16
3    D     92   17
0    A     85   15
2    C     70   15

In [18]:
# Name column ke ascending order me sort karo.
s=df.sort_values(["name"],ascending=True)
print(s)

  name  marks  age
0    A     85   15
1    B     92   16
2    C     70   15
3    D     92   17

In [20]:
# Index ko descending order me sort karo.
s=df.sort_index(ascending=True)
s

  name  marks  age
0    A     85   15
1    B     92   16
2    C     70   15
3    D     92   17

In [23]:
# Marks aur name ke combination se sort karo:
s=df.sort_values(by=["marks","name"],ascending=True)
s

  name  marks  age
2    C     70   15
0    A     85   15
1    B     92   16
3    D     92   17

In [27]:
# Marks descending
s=df.sort_values(["marks"],ascending=True)
s

  name  marks  age
2    C     70   15
0    A     85   15
1    B     92   16
3    D     92   17

In [ ]:
# # Name ascending (tie-break)
# Hum ek column (jaise marks) se sort kar rahe hain
# Agar do ya do se zyada rows ke marks same ho → tie ho gaya
# Ab tie-break ke liye dusre column ka use karte hain (jaise name)

In [30]:
# Age aur Marks ke combination me sort karo, dono ascending.
d=df.sort_values(["age","marks"],ascending=[True,True])
print(d)

  name  marks  age
2    C     70   15
0    A     85   15
1    B     92   16
3    D     92   17

In [46]:
# Marks ke equal rows me age descending, baki ascending.
df.sort_values(by="marks", ascending=False, inplace=True)
print(df)

  name  marks  age  salary
3    D     92   17    7000
1    B     92   16    6000
0    A     85   15    5000
2    C     70   15    4500

In [39]:
# Ek column “salary” add karo [5000, 6000, 4500, 7000] → salary descending order me sort karo.
df["salary"] = [5000, 6000, 4500, 7000]
d=df.sort_values(["salary"],ascending=False)
print(d)

  name  marks  age  salary
3    D     92   17    7000
1    B     92   16    6000
0    A     85   15    5000
2    C     70   15    4500

In [40]:
# Sort ke baad sirf top 2 rows select karo.
sd=d.head(2)
print(sd)

  name  marks  age  salary
3    D     92   17    7000
1    B     92   16    6000

In [45]:
df.sort_values(by="marks", ascending=False, inplace=True)
print(df)

  name  marks  age  salary
3    D     92   17    7000
1    B     92   16    6000
0    A     85   15    5000
2    C     70   15    4500

In [49]:
# Marks > 80 wale rows filter karo.
s=df.query("marks>80")
print(s)

  name  marks  age  salary
3    D     92   17    7000
1    B     92   16    6000
0    A     85   15    5000

In [50]:
# Age <= 16 aur marks > 80 wale rows filter karo.
s=df.query("age <= 16 & marks > 80")
print(s)

  name  marks  age  salary
3    D     92   17    7000
1    B     92   16    6000
0    A     85   15    5000
2    C     70   15    4500

In [52]:
# Name = “C” ya marks < 80 wale rows filter karo.
s=df.query("name == 'C' | marks < 80")
print(s)

  name  marks  age  salary
2    C     70   15    4500

In [56]:
# Ek variable min_marks = 80 banakar query me use karo.
min_marks = 80
d=df.query("marks>@min_marks")
print(d)

  name  marks  age  salary
3    D     92   17    7000
1    B     92   16    6000
0    A     85   15    5000

In [58]:
# Marks > min_marks aur age < 17 wale rows query karo using @min_marks.
min_marks = 80
d=df.query("marks> @min_marks & age < 17")
print(d)

  name  marks  age  salary
1    B     92   16    6000
0    A     85   15    5000

In [59]:
# Name column me “A” ya “D” ke rows filter karo using .query().
aname="A"
dname="D"
d=df.query("name == @aname | name == @dname")
print(d)

  name  marks  age  salary
3    D     92   17    7000
0    A     85   15    5000

In [63]:
# Marks 70–90 ke beech wale rows select karo using query.
d=df.query("70<marks<90")
d

  name  marks  age  salary
0    A     85   15    5000

In [64]:
# Age = 15 ya marks = 92 wale rows select karo.
d=df.query("age == 15 | marks == 92")
print(d)

  name  marks  age  salary
3    D     92   17    7000
1    B     92   16    6000
0    A     85   15    5000
2    C     70   15    4500

In [67]:
# Query me AND + OR combination ka use karo:
# Age < 17 AND marks > 80
# OR name = "C"
s=df.query("(age<17 & marks >80)| name == 'C'")
print(s)

  name  marks  age  salary
1    B     92   16    6000
0    A     85   15    5000
2    C     70   15    4500

In [ ]:
# Query aur sort combine kar ke:
# Marks > 80 rows filter karo
# Uske baad marks descending aur age ascending order me sort karo
s=df.query("marks > 80")
ss=s.sort_values(by=["marks","age"],ascending=[True,True])
print(s)
print(ss)

# Phase 7

In [3]:

import pandas as pd

df = pd.DataFrame({
    "department": ["HR", "IT", "HR", "IT", "Finance"],
    "employee": ["A", "B", "C", "D", "E"],
    "salary": [5000, 7000, 6000, 8000, 9000],
    "bonus": [500, 600, 400, 700, 900]
})
df

  department employee  salary  bonus
0         HR        A    5000    500
1         IT        B    7000    600
2         HR        C    6000    400
3         IT        D    8000    700
4    Finance        E    9000    900

In [2]:
#1️⃣ Sum of salary per department
df.groupby("department")["salary"].sum()

department
Finance     9000
HR         11000
IT         15000
Name: salary, dtype: int64

In [15]:
# Keep department as column (as_index=False)
d=df.groupby("department" ,as_index=False)["salary"].sum()
print(d)

  department  salary
0    Finance    9000
1         HR   11000
2         IT   15000

In [16]:
#Multi-level index (group by multiple columns)
df.groupby(["department","employee"])["salary"].sum()

department  employee
Finance     E           9000
HR          A           5000
            C           6000
IT          B           7000
            D           8000
Name: salary, dtype: int64

In [18]:
# Reset index
df.groupby(["department","employee"],as_index=False)["salary"].sum()

  department employee  salary
0    Finance        E    9000
1         HR        A    5000
2         HR        C    6000
3         IT        B    7000
4         IT        D    8000

In [22]:
# Swap level (useful for MultiIndex)
multi=df.groupby(["department","employee"])["salary"].sum()
multi_swapped=multi.swaplevel()
print(multi_swapped)

employee  department
E         Finance       9000
A         HR            5000
C         HR            6000
B         IT            7000
D         IT            8000
Name: salary, dtype: int64

In [23]:
# Aggregation
# 1️⃣ Single aggregation
df.groupby("department")["salary"].sum()

department
Finance     9000
HR         11000
IT         15000
Name: salary, dtype: int64

In [24]:
# 2️⃣ Multiple aggregation
df.groupby("department")["salary"].agg(["sum","mean"])

              sum    mean
department
Finance      9000  9000.0
HR          11000  5500.0
IT          15000  7500.0

In [39]:
# Per-column aggregation using dictionary

df.groupby("department").agg({
    "salary":"sum",
    "bonus": "mean"
}
)

            salary  bonus
department
Finance       9000  900.0
HR           11000  450.0
IT           15000  650.0

In [30]:
# Naming aggregated columns
df.groupby("department").agg(
    total_salary=("salary","sum"),
    avg_bonus=("bonus","mean")
)

            total_salary  avg_bonus
department
Finance             9000      900.0
HR                 11000      450.0
IT                 15000      650.0

In [31]:
# Transform ()
df.groupby("department")["salary"].transform("mean")

0    5500.0
1    7500.0
2    5500.0
3    7500.0
4    9000.0
Name: salary, dtype: float64

In [42]:
df.groupby(["department","employee"])["salary"].sum()

department  employee
Finance     E           9000
HR          A           5000
            C           6000
IT          B           7000
            D           8000
Name: salary, dtype: int64

In [43]:
df.groupby(["department","employee"])["salary"].sum().reset_index()

  department employee  salary
0    Finance        E    9000
1         HR        A    5000
2         HR        C    6000
3         IT        B    7000
4         IT        D    8000

In [45]:
d=df.groupby(["department","employee"])["salary"].sum()
swap=d.swaplevel()
print(swap)

employee  department
E         Finance       9000
A         HR            5000
C         HR            6000
B         IT            7000
D         IT            8000
Name: salary, dtype: int64

In [49]:
df["Max_Sal"]=df.groupby("department")["salary"].transform("max")
print(df["department"],df["Max_Sal"])

0         HR
1         IT
2         HR
3         IT
4    Finance
Name: department, dtype: object 0    6000
1    8000
2    6000
3    8000
4    9000
Name: Max_Sal, dtype: int64

In [50]:
# Salary Normalization inside group
df["normalization"]=df["salary"]/df.groupby("department")["salary"].transform("sum")
print(df["normalization"])

0    0.454545
1    0.466667
2    0.545455
3    0.533333
4    1.000000
Name: normalization, dtype: float64

In [6]:
# Fill Missing Age with Department-wise Median
df["age"]=df["age"].fillna(
    df.groupby("department")["age"].transform("median")
)

  department employee  salary  bonus
0         HR        A    5000    500
1         IT        B    7000    600
2         HR        C    6000    400
3         IT        D    8000    700
4    Finance        E    9000    900

# prectise questions

In [2]:
import pandas as pd

df = pd.DataFrame({
    "department": ["HR","IT","HR","Finance","IT","Finance","HR","IT","Finance","HR"],
    "employee":   ["A","B","C","D","E","F","G","H","I","J"],
    "salary":     [5000,7000,6000,9000,8000,9500,5500,7200,8800,6200],
    "age":        [25,30,28,40,35,42,26,33,41,27],
    "city":       ["Delhi","Mumbai","Delhi","Pune","Mumbai","Pune","Delhi","Delhi","Pune","Mumbai"]
})

print(df)

  department employee  salary  age    city
0         HR        A    5000   25   Delhi
1         IT        B    7000   30  Mumbai
2         HR        C    6000   28   Delhi
3    Finance        D    9000   40    Pune
4         IT        E    8000   35  Mumbai
5    Finance        F    9500   42    Pune
6         HR        G    5500   26   Delhi
7         IT        H    7200   33   Delhi
8    Finance        I    8800   41    Pune
9         HR        J    6200   27  Mumbai

In [10]:
# Find department-wise total salary.
pd=df.groupby("department")["salary"].sum()
print(pd)

department
Finance    27300
HR         22700
IT         22200
Name: salary, dtype: int64

In [12]:
# Find department-wise average age (use as_index=False).
pd=df.groupby("department",as_index=False)["age"].mean()
print(pd)

  department        age
0    Finance  41.000000
1         HR  26.500000
2         IT  32.666667

In [13]:
# Find city-wise employee count.
pd=df.groupby("city")["employee"].count()
print(pd)

city
Delhi     4
Mumbai    3
Pune      3
Name: employee, dtype: int64

In [14]:
# Find salary sum by (Department + City) combination.
pd=df.groupby(["department","city"])["salary"].sum()
print(pd)

department  city
Finance     Pune      27300
HR          Delhi     16500
            Mumbai     6200
IT          Delhi      7200
            Mumbai    15000
Name: salary, dtype: int64

In [19]:
# For each department, calculate sum, mean, max of salary (in one line).
pd=df.groupby(["department"])["salary"].agg(["sum","mean","max"]) 
print(pd)

              sum    mean   max
department
Finance     27300  9100.0  9500
HR          22700  5675.0  6200
IT          22200  7400.0  8000

In [25]:
# Department-wise calculate:
# total_salary
# avg_age
# and rename the columns.
pd=df.groupby(["department"]).agg({
    "salary":"sum",
    "age":"mean"
}
)
print(pd)

pd=df.groupby(["department"]).agg(
    Total_salary=("salary","sum"),
    Avg_Age=("age","mean")
)
print(pd)

            salary        age
department
Finance      27300  41.000000
HR           22700  26.500000
IT           22200  32.666667
            Total_salary    Avg_Age
department
Finance            27300  41.000000
HR                 22700  26.500000
IT                 22200  32.666667

In [31]:
# Find the total salary of only the HR department (using groupby + filter).
pd=df.groupby("department").filter(lambda x : x.name=="HR")["salary"].sum()
print(pd)

22700

In [37]:
# Get the employee list grouped by department (only groupby, no aggregation).
pd=df.groupby("department")["employee"].apply(list)
print(pd)

department
Finance       [D, F, I]
HR         [A, C, G, J]
IT            [B, E, H]
Name: employee, dtype: object

In [41]:
# Find department-wise minimum age and then apply reset_index().
pd=df.groupby("department")["age"].min().reset_index()
print(pd)

  department  age
0    Finance   40
1         HR   25
2         IT   30

In [44]:
# From a multi-index output (Dept → City), swap levels so it becomes (City → Dept).
pd=df.groupby(["department","city"])["salary"].sum()
swap=pd.swaplevel()
print(swap)
print("***********************************")
print(pd)

city    department
Pune    Finance       27300
Delhi   HR            16500
Mumbai  HR             6200
Delhi   IT             7200
Mumbai  IT            15000
Name: salary, dtype: int64
***********************************
department  city
Finance     Pune      27300
HR          Delhi     16500
            Mumbai     6200
IT          Delhi      7200
            Mumbai    15000
Name: salary, dtype: int64

In [45]:
# 11. For each row, show the department’s average salary
# (using .transform('mean')).
pd=df.groupby("department")["salary"].transform("mean")
print(pd)

0    5675.0
1    7400.0
2    5675.0
3    9100.0
4    7400.0
5    9100.0
6    5675.0
7    7400.0
8    9100.0
9    5675.0
Name: salary, dtype: float64

In [24]:
# 12. For each employee, compute:

# salary − department_max_salary
# (groupby + transform)
pd=df.groupby("department")["salary"].transform("max")
sal_dep=df["salary"]-pd
print(sal_dep)

0   -1200
1   -1000
2    -200
3    -500
4       0
5       0
6    -700
7    -800
8    -700
9       0
Name: salary, dtype: int64

In [26]:
# Normalize salary using:
# salary / department_salary_sum
pd=df.groupby("department")["salary"].transform("sum")
df["normalized_Salary"]=df["salary"]/pd
df

  department employee  salary  age    city  normalized_Salary
0         HR        A    5000   25   Delhi           0.220264
1         IT        B    7000   30  Mumbai           0.315315
2         HR        C    6000   28   Delhi           0.264317
3    Finance        D    9000   40    Pune           0.329670
4         IT        E    8000   35  Mumbai           0.360360
5    Finance        F    9500   42    Pune           0.347985
6         HR        G    5500   26   Delhi           0.242291
7         IT        H    7200   33   Delhi           0.324324
8    Finance        I    8800   41    Pune           0.322344
9         HR        J    6200   27  Mumbai           0.273128

In [31]:
# Find department-wise median age,
# and fill missing ages (NaN) with the median of that department.
median_age=df.groupby("department")["age"].transform("mean")
df["age"]=df["age"].fillna(median_age)
print(df)

  department employee  salary  age    city  normalized_Salary
0         HR        A    5000   25   Delhi           0.220264
1         IT        B    7000   30  Mumbai           0.315315
2         HR        C    6000   28   Delhi           0.264317
3    Finance        D    9000   40    Pune           0.329670
4         IT        E    8000   35  Mumbai           0.360360
5    Finance        F    9500   42    Pune           0.347985
6         HR        G    5500   26   Delhi           0.242291
7         IT        H    7200   33   Delhi           0.324324
8    Finance        I    8800   41    Pune           0.322344
9         HR        J    6200   27  Mumbai           0.273128

In [37]:
# Get the employee with highest salary in each department.
# (Hint: groupby().salary.idxmax())
pd=df.groupby("department")["salary"].transform("max")
print(pd)
idx = df.groupby("department")["salary"].idxmax()
highest_salary_emp = df.loc[idx]
print(highest_salary_emp)

  department employee  salary  age    city  normalized_Salary
5    Finance        F    9500   42    Pune           0.347985
9         HR        J    6200   27  Mumbai           0.273128
4         IT        E    8000   35  Mumbai           0.360360

In [43]:
# Find city-wise average salary and broadcast it to each row using transform.
idx=df.groupby("department")["salary"].idxmax()
highest_salary_emp= df.loc[idx]
print(highest_salary_emp)

  department employee  salary  age    city  normalized_Salary
5    Finance        F    9500   42    Pune           0.347985
9         HR        J    6200   27  Mumbai           0.273128
4         IT        E    8000   35  Mumbai           0.360360

In [45]:
# Calculate department-wise salary variance (var) and standard deviation (std).
pd=df.groupby("department")["salary"].agg(["var","std"])
print(pd)

                      var         std
department
Finance     130000.000000  360.555128
HR          289166.666667  537.742193
IT          280000.000000  529.150262

In [46]:
# Find department-wise employee count,
# and sort in descending order.
pd=df.groupby("department")["employee"].count().sort_values(ascending=False)
print(pd)

department
HR         4
Finance    3
IT         3
Name: employee, dtype: int64

In [47]:
# Create an aggregated DataFrame:
# salary → mean
# age → max
# employee → count
pd=df.groupby("department").agg({
    "salary":"mean",
    "age":"max",
    "employee":"count"
})
pd

            salary  age  employee
department
Finance     9100.0   42         3
HR          5675.0   28         4
IT          7400.0   35         3

In [18]:
# Rename the aggregated columns to:
# avg_salary
# max_age
# emp_count
df=df.rename(columns={
    "salary":"salary",
    "age":"age",
    "name":"name"
})
print(df)

  department employee  avg_salary  avg_age    city
0         HR        A        5000       25   Delhi
1         IT        B        7000       30  Mumbai
2         HR        C        6000       28   Delhi
3    Finance        D        9000       40    Pune
4         IT        E        8000       35  Mumbai
5    Finance        F        9500       42    Pune
6         HR        G        5500       26   Delhi
7         IT        H        7200       33   Delhi
8    Finance        I        8800       41    Pune
9         HR        J        6200       27  Mumbai

In [22]:
df=df.rename(columns={
    "avg_salary":"salary",
    "avg_age":"age",
    "name":"name"
})

  department employee  salary  age    city
0         HR        A    5000   25   Delhi
1         IT        B    7000   30  Mumbai
2         HR        C    6000   28   Delhi
3    Finance        D    9000   40    Pune
4         IT        E    8000   35  Mumbai
5    Finance        F    9500   42    Pune
6         HR        G    5500   26   Delhi
7         IT        H    7200   33   Delhi
8    Finance        I    8800   41    Pune
9         HR        J    6200   27  Mumbai

In [49]:
# Department-wise salary sum print karo.
pd=df.groupby("department")["salary"].sum()
print(pd)

department
Finance    27300
HR         22700
IT         22200
Name: salary, dtype: int64

In [51]:
# City-wise average salary print karo.
pd=df.groupby("city")["salary"].mean()
pd

city
Delhi     5925.000000
Mumbai    7066.666667
Pune      9100.000000
Name: salary, dtype: float64

In [54]:
# Department-wise minimum age print karo.
pd=df.groupby("department")["age"].min()
print(pd)

department
Finance    40
HR         25
IT         30
Name: age, dtype: int64

In [55]:
# Department-wise maximum salary print karo.
pd=df.groupby("department")["salary"].max()
print(pd)

department
Finance    9500
HR         6200
IT         8000
Name: salary, dtype: int64

In [57]:
# Department-wise salary ka mean aur sum ek saath print karo.
pd=df.groupby("department")["salary"].agg(["mean","sum"])
print(pd)

              mean    sum
department
Finance     9100.0  27300
HR          5675.0  22700
IT          7400.0  22200

In [59]:
# Department-wise data ko as_index=False karke print karo.
pd=df.groupby("department",as_index=False)["salary"].sum()
print(pd)

  department  salary
0    Finance   27300
1         HR   22700
2         IT   22200

In [61]:
# Two-column group: department–city salary sum.
pd=df.groupby(["department","city"])["salary"].sum()
print(pd)

department  city
Finance     Pune      27300
HR          Delhi     16500
            Mumbai     6200
IT          Delhi      7200
            Mumbai    15000
Name: salary, dtype: int64

In [62]:
# Department-wise multiple columns aggregate (salary mean, age max).
pd=df.groupby("department").agg({
    "salary":"mean",
    "age":"max"
})
print(pd)

            salary  age
department
Finance     9100.0   42
HR          5675.0   28
IT          7400.0   35

In [66]:
# Department-wise sorted salary sum (descending).
pd=df.groupby("department")["salary"].sum().sort_values(ascending=True)
print(pd)

department
IT         22200
HR         22700
Finance    27300
Name: salary, dtype: int64

In [67]:
# Department-wise employee list (without aggregation).
pd=df.groupby("department")["employee"].apply(list)
print(pd)

department
Finance       [D, F, I]
HR         [A, C, G, J]
IT            [B, E, H]
Name: employee, dtype: object

In [3]:
# Department-wise salary count.
pd=df.groupby("department")["salary"].count()
print(pd)

department
Finance    3
HR         4
IT         3
Name: salary, dtype: int64

In [7]:
# Multi-index swaplevel practice.
pd=df.groupby(["city","department"])["salary"].sum()
d=pd.swaplevel()
print(d)

department  city
HR          Delhi     16500
IT          Delhi      7200
HR          Mumbai     6200
IT          Mumbai    15000
Finance     Pune      27300
Name: salary, dtype: int64

In [21]:
# Department-wise salary range (max – min).
pd=df.groupby("department")["salary"].agg({"max","min"})
print(pd)

pd=df.groupby("department")["salary"].agg(lambda x : x.max() - x.min())
print(pd)
print(df.groupby("department")["salary"].agg(salary_range=lambda x :x.max() - x.min()))

             min   max
department
Finance     8800  9500
HR          5000  6200
IT          7000  8000
department
Finance     700
HR         1200
IT         1000
Name: salary, dtype: int64
            salary_range
department
Finance              700
HR                  1200
IT                  1000

In [16]:
# City-wise average age (with renamed columns).
pd=df.groupby("city").agg({
    "age":"mean"
})
print(pd)


pd=df.groupby("city")["age"].agg(ranamed_Age="mean")
print(pd)

        ranamed_Age
city
Delhi     28.000000
Mumbai    30.666667
Pune      41.000000

In [17]:
# Department-wise employee names ko list me convert karo.
pd=df.groupby("department")["employee"].apply(list)
print(pd)

department
Finance       [D, F, I]
HR         [A, C, G, J]
IT            [B, E, H]
Name: employee, dtype: object

In [23]:
# Department-wise salary ka 90th percentile.
pd=df.groupby("department")["salary"].quantile(0.90)
print(pd)

department
Finance    9400.0
HR         6140.0
IT         7840.0
Name: salary, dtype: float64

In [24]:
# Department-wise salary standard deviation.
pd=df.groupby("department")["salary"].std()
print(pd)

department
Finance    360.555128
HR         537.742193
IT         529.150262
Name: salary, dtype: float64

In [29]:
# Groupby karke sirf HR department ka sum nikalo.
#print(df[df["department"] == "HR"]["salary"].sum())
pd=df.groupby("department")["salary"].sum()
print(pd.loc["HR"])

22700

In [31]:
# Department-wise top 2 salary employees.
pd=df.sort_values("salary",ascending=False).groupby("department").head(2)
print(pd)

  department employee  salary  age    city
5    Finance        F    9500   42    Pune
3    Finance        D    9000   40    Pune
4         IT        E    8000   35  Mumbai
7         IT        H    7200   33   Delhi
9         HR        J    6200   27  Mumbai
2         HR        C    6000   28   Delhi

In [33]:
# Each row → department average salary.
pd=df.groupby("department")["salary"].transform("mean")
print(pd)
pd=df.groupby("department")["salary"].mean()
print(pd)

0    5675.0
1    7400.0
2    5675.0
3    9100.0
4    7400.0
5    9100.0
6    5675.0
7    7400.0
8    9100.0
9    5675.0
Name: salary, dtype: float64
department
Finance    9100.0
HR         5675.0
IT         7400.0
Name: salary, dtype: float64

In [34]:
# Salary difference: salary – dept_max_salary.
pd=df.groupby("department")["salary"].transform("max")
print("salary diffenrece:",df["salary"]-pd)

salary diffenrece: 0   -1200
1   -1000
2    -200
3    -500
4       0
5       0
6    -700
7    -800
8    -700
9       0
Name: salary, dtype: int64

In [35]:
# Normalized salary: salary / dept_sum_salary.
pd=df.groupby("department")["salary"].transform("sum")
print("Normalized salary:",df["salary"]/pd)

Normalized salary: 0    0.220264
1    0.315315
2    0.264317
3    0.329670
4    0.360360
5    0.347985
6    0.242291
7    0.324324
8    0.322344
9    0.273128
Name: salary, dtype: float64

In [46]:
# Department-wise median age → fill missing ages.
df["pd"]=df.groupby("department")["age"].transform("median")
df["filled_Age"]=df["age"].fillna(df["pd"])
print(df["filled_Age"])

df["age"]=df["age"].fillna(df.groupby("department")["age"].transform("median"))
print(df["age"])

0    25
1    30
2    28
3    40
4    35
5    42
6    26
7    33
8    41
9    27
Name: filled_Age, dtype: int64
0    25
1    30
2    28
3    40
4    35
5    42
6    26
7    33
8    41
9    27
Name: age, dtype: int64

In [50]:
# Salary z-score per department.
#Formula: (x − mean) / std
df["salarymean"]=df.groupby("department")["salary"].transform("mean")
df["salarystd"]=df.groupby("department")["salary"].transform("std")
df["z_score"]=(df["salary"]-df["salarymean"])/df["salarystd"]
print(df["salarymean"])
print(df["salarystd"])
print(df["z_score"])

0    5675.0
1    7400.0
2    5675.0
3    9100.0
4    7400.0
5    9100.0
6    5675.0
7    7400.0
8    9100.0
9    5675.0
Name: salarymean, dtype: float64
0    537.742193
1    529.150262
2    537.742193
3    360.555128
4    529.150262
5    360.555128
6    537.742193
7    529.150262
8    360.555128
9    537.742193
Name: salarystd, dtype: float64
0   -1.255248
1   -0.755929
2    0.604379
3   -0.277350
4    1.133893
5    1.109400
6   -0.325435
7   -0.377964
8   -0.832050
9    0.976304
Name: z_score, dtype: float64

In [56]:
# Rank employees within each department.
df["pd"]=df.groupby("department")["salary"].rank(ascending=False)
print(df["pd"])
df["dept_rank"] = df.groupby("department")["salary"].rank(ascending=False)
print(df["dept_rank"])

0    4.0
1    3.0
2    2.0
3    2.0
4    1.0
5    1.0
6    3.0
7    2.0
8    3.0
9    1.0
Name: pd, dtype: float64
0    4.0
1    3.0
2    2.0
3    2.0
4    1.0
5    1.0
6    3.0
7    2.0
8    3.0
9    1.0
Name: dept_rank, dtype: float64

In [61]:
# Flag top salary employee (1/0).
df["is_dept_rank"]=(df["dept_rank"]==1).astype(int)
print(df["is_dept_rank"])

0    0
1    0
2    0
3    0
4    1
5    1
6    0
7    0
8    0
9    1
Name: is_dept_rank, dtype: int64

In [65]:
# Salary percentage share per department.
df["pd"]=df.groupby("department")["salary"].transform("sum")
print(df["salary"]/df["pd"])


#second way
print(df["salary"]/df.groupby("department")["salary"].transform("sum"))

0    0.220264
1    0.315315
2    0.264317
3    0.329670
4    0.360360
5    0.347985
6    0.242291
7    0.324324
8    0.322344
9    0.273128
dtype: float64
0    0.220264
1    0.315315
2    0.264317
3    0.329670
4    0.360360
5    0.347985
6    0.242291
7    0.324324
8    0.322344
9    0.273128
Name: salary, dtype: float64

In [67]:
# For each city → fill avg salary in new col.
df["new_avg"]=df.groupby("city")["salary"].transform("mean")
print(df)

  department employee  salary  age    city  26.5  33.0  41.0     pd  \
0         HR        A    5000   25   Delhi  26.5  33.0  41.0  22700
1         IT        B    7000   30  Mumbai  26.5  33.0  41.0  22200
2         HR        C    6000   28   Delhi  26.5  33.0  41.0  22700
3    Finance        D    9000   40    Pune  26.5  33.0  41.0  27300
4         IT        E    8000   35  Mumbai  26.5  33.0  41.0  22200
5    Finance        F    9500   42    Pune  26.5  33.0  41.0  27300
6         HR        G    5500   26   Delhi  26.5  33.0  41.0  22700
7         IT        H    7200   33   Delhi  26.5  33.0  41.0  22200
8    Finance        I    8800   41    Pune  26.5  33.0  41.0  27300
9         HR        J    6200   27  Mumbai  26.5  33.0  41.0  22700

   filled_Age  ...   salarystd   z_Score   z_score  1.0  2.0  3.0  4.0  \
0          25  ...  537.742193 -1.255248 -1.255248  2.0  1.0  3.0  1.0
1          30  ...  529.150262 -0.755929 -0.755929  2.0  1.0  3.0  1.0
2          28  ...  537.742193  0.604379  0.604379  2.0  1.0  3.0  1.0
3          40  ...  360.555128 -0.277350 -0.277350  2.0  1.0  3.0  1.0
4          35  ...  529.150262  1.133893  1.133893  2.0  1.0  3.0  1.0
5          42  ...  360.555128  1.109400  1.109400  2.0  1.0  3.0  1.0
6          26  ...  537.742193 -0.325435 -0.325435  2.0  1.0  3.0  1.0
7          33  ...  529.150262 -0.377964 -0.377964  2.0  1.0  3.0  1.0
8          41  ...  360.555128 -0.832050 -0.832050  2.0  1.0  3.0  1.0
9          27  ...  537.742193  0.976304  0.976304  2.0  1.0  3.0  1.0

   dept_rank  is_dept_rank      new_avg
0        4.0             0  5925.000000
1        3.0             0  7066.666667
2        2.0             0  5925.000000
3        2.0             0  9100.000000
4        1.0             1  7066.666667
5        1.0             1  9100.000000
6        3.0             0  5925.000000
7        2.0             0  5925.000000
8        3.0             0  9100.000000
9        1.0             1  7066.666667

[10 rows x 21 columns]

In [68]:
# For each row → department-wise min salary.
df["min_sal"]=df.groupby("department")["salary"].transform("min")
df

,department,employee,salary,age,city,26.5,33.0,41.0,pd,filled_Age,...,z_Score,z_score,1.0,2.0,3.0,4.0,dept_rank,is_dept_rank,new_avg,min_sal
0,HR,A,5000,25,Delhi,26.5,33.0,41.0,22700,25,...,-1.255248,-1.255248,2.0,1.0,3.0,1.0,4.0,0,5925.000000,5000
1,IT,B,7000,30,Mumbai,26.5,33.0,41.0,22200,30,...,-0.755929,-0.755929,2.0,1.0,3.0,1.0,3.0,0,7066.666667,7000
2,HR,C,6000,28,Delhi,26.5,33.0,41.0,22700,28,...,0.604379,0.604379,2.0,1.0,3.0,1.0,2.0,0,5925.000000,5000
3,Finance,D,9000,40,Pune,26.5,33.0,41.0,27300,40,...,-0.277350,-0.277350,2.0,1.0,3.0,1.0,2.0,0,9100.000000,8800
4,IT,E,8000,35,Mumbai,26.5,33.0,41.0,22200,35,...,1.133893,1.133893,2.0,1.0,3.0,1.0,1.0,1,7066.666667,7000
5,Finance,F,9500,42,Pune,26.5,33.0,41.0,27300,42,...,1.109400,1.109400,2.0,1.0,3.0,1.0,1.0,1,9100.000000,8800
6,HR,G,5500,26,Delhi,26.5,33.0,41.0,22700,26,...,-0.325435,-0.325435,2.0,1.0,3.0,1.0,3.0,0,5925.000000,5000
7,IT,H,7200,33,Delhi,26.5,33.0,41.0,22200,33,...,-0.377964,-0.377964,2.0,1.0,3.0,1.0,2.0,0,5925.000000,7000
8,Finance,I,8800,41,Pune,26.5,33.0,41.0,27300,41,...,-0.832050,-0.832050,2.0,1.0,3.0,1.0,3.0,0,9100.000000,8800
9,HR,J,6200,27,Mumbai,26.5,33.0,41.0,22700,27,...,0.976304,0.976304,2.0,1.0,3.0,1.0,1.0,1,7066.666667,5000

In [69]:
# Q1 — Department-wise salary MAD (Median Absolute Deviation) apply() se nikalo.
# (Median to nikalna simple hota hai, par MAD apply() se karna expert-level hai)
pd=df.groupby("department")["salary"].median()
print(pd)

department
Finance    9000.0
HR         5750.0
IT         7200.0
Name: salary, dtype: float64

# Pivoting And Reshaping

In [81]:
import pandas as pd

df = pd.DataFrame({
    'city': ['Delhi', 'Delhi', 'Mumbai', 'Mumbai'],
    'product': ['A', 'B', 'A', 'B'],
    'sales': [100, 150, 200, 300]
})

In [74]:
pd.pivot_table(df,
               index='city',
               columns='product',
               values='sales',
               aggfunc='sum'
)

product    A    B
city
Delhi    100  150
Mumbai   200  300

In [77]:
pd.pivot_table(df,
              index='product',
              columns='city',
              values='sales',
              aggfunc='sum')

city     Delhi  Mumbai
product
A          100     200
B          150     300

In [78]:
pd.pivot_table(df,
              index='product',
              columns='city',
              values='sales',
              aggfunc=['sum','mean'])

          sum          mean
city    Delhi Mumbai  Delhi Mumbai
product
A         100    200  100.0  200.0
B         150    300  150.0  300.0

In [124]:
df = pd.DataFrame({
    'city':['Delhi','Delhi','Delhi','Mumbai','Mumbai'],
    'product':['A','A','B','A','A'],
    'sales':[100,50,150,200,100]
})

In [80]:
pd.pivot_table(df,
              index="city",
              columns="product",
              values="sales",
              aggfunc="sum")

product      A      B
city
Delhi    150.0  150.0
Mumbai   300.0    NaN

In [123]:
pd.pivot_table(df,
              index="city",
              columns="product",
              values="sales",
              aggfunc="sum",
              margins=True)

product      A      B  All
city
Delhi    150.0  150.0  300
Mumbai   300.0    NaN  300
All      450.0  150.0  600

In [125]:
df = pd.DataFrame({
    'city': ['Delhi','Mumbai'],
    'A': [100, 200],
    'B': [150, 300]
})
df

     city    A    B
0   Delhi  100  150
1  Mumbai  200  300

In [126]:
df.melt(
       id_vars='city',
       var_name="product",
       value_name="sales")

     city product  sales
0   Delhi       A    100
1  Mumbai       A    200
2   Delhi       B    150
3  Mumbai       B    300

In [104]:
import pandas as pd
df = pd.DataFrame({
    'city': ['Delhi', 'Delhi', 'Mumbai', 'Mumbai'],
    'product': ['A', 'B', 'A', 'B'],
    'sales': [100, 150, 200, 300]
})
pt = df.pivot_table(index='city', columns='product', values='sales', aggfunc='sum')
pt.stack()

city    product
Delhi   A          100
        B          150
Mumbai  A          200
        B          300
dtype: int64

In [107]:
pd.pivot_table(df,index='city', columns='product', values='sales', aggfunc='sum')

product    A    B
city
Delhi    100  150
Mumbai   200  300

In [111]:
s = df.groupby(['city','product'])['sales'].sum()
s.unstack()

product    A    B
city
Delhi    100  150
Mumbai   200  300

In [127]:
df.melt(
    id_vars="city",
    var_name="product",
    value_name="sales"
)

     city product  sales
0   Delhi       A    100
1  Mumbai       A    200
2   Delhi       B    150
3  Mumbai       B    300

In [128]:
df=pd.DataFrame(
    {
        "City":["Delhi","Delhi","Mumbai","Mumbai"],
        "product":["A","B","A","B"],
        "sales":[100,150,200,300]
    }
)

     City product  sales
0   Delhi       A    100
1   Delhi       B    150
2  Mumbai       A    200
3  Mumbai       B    300

In [130]:
#pivot Table 
df.pivot_table(index="City",columns="product",values="sales",aggfunc="sum")

product    A    B
City
Delhi    100  150
Mumbai   200  300

In [ ]:
city | product | sales
Delhi   A       100
Delhi   A       80
Delhi   B       120
Mumbai  A       200
Mumbai  A       200
Mumbai  B       300

In [131]:
df=pd.DataFrame({
    "city":["Delhi","Delhi","Delhi","Mumbai","Mumbai","Mumbai"],
    "product":["A","A","B","A","A","B"],
    "Sales":[100,80,120,200,200,300]
})
#sum,mean,count

     city product  Sales
0   Delhi       A    100
1   Delhi       A     80
2   Delhi       B    120
3  Mumbai       A    200
4  Mumbai       A    200
5  Mumbai       B    300

In [133]:
df.pivot_table(index="city",columns="product",values="Sales",aggfunc=["sum","mean","count"])

         sum        mean        count
product    A    B      A      B     A  B
city
Delhi    180  120   90.0  120.0     2  1
Mumbai   400  300  200.0  300.0     2  1

In [135]:
# Q5. margins=True lagao, "All" row/column kis tarah banti hai?

# (Total manually calculate karo)
df.pivot_table(index="city",columns="product",values="Sales",aggfunc="sum",margins=True)

product    A    B   All
city
Delhi    180  120   300
Mumbai   400  300   700
All      580  420  1000

In [ ]:
#Agar ek city ka ek product missing ho to pivot kya show karega? (NaN/mm?)
Nan

In [12]:
# 🔥 LEVEL-2: GroupBy vs Pivot (Difference seeing)
# Q7. Same DataFrame ko:

# groupby(['city','product'])['sales'].sum()

# pivot_table index=city, columns=product

# → Compare output shape
# → Kaun Series? Kaun DataFrame?
# → Kaun matrix shape deta?
import pandas as pd
df=pd.DataFrame({
    "city":["Delhi","Delhi","Delhi","Mumbai","Mumbai","Mumbai"],
    "product":["A","A","B","A","A","B"],
    "Sales":[100,80,120,200,200,300]
})
# group by 
s=df.groupby("city")["Sales"].count()
print(s)

# Pivot table
s=df.pivot_table(index="city",columns="product",values="Sales",aggfunc="count")

print(s)

city
Delhi     3
Mumbai    3
Name: Sales, dtype: int64
product  A  B
city
Delhi    2  1
Mumbai   2  1

In [19]:
# Q8. GroupBy ke result ko unstack() kar ke pivot ka same output banao.
# (Logic: groupby → sum → unstack())
s=df.groupby(["city","product"])["Sales"].sum().unstack()
print(s)

product    A    B
city
Delhi    180  120
Mumbai   400  300

In [22]:
# 🔥 LEVEL-3: UNPIVOT — melt()
# Q9. Ye DataFrame lo:
# city | A | B | C
# Delhi 100 150 200
# Mumbai 80  120 140
# → melt() use karke unpivot banao
# id_vars=city
# var_name=product
# value_name=value
df = pd.DataFrame({
    "city": ["Delhi","Mumbai"],
    "A": [100,80],
    "B": [150,120],
    "C": [200,140]
})
d=df.melt(id_vars="city",var_name="product",value_name="value")
d

     city product  value
0   Delhi       A    100
1  Mumbai       A     80
2   Delhi       B    150
3  Mumbai       B    120
4   Delhi       C    200
5  Mumbai       C    140

In [24]:
# Q10. Agar main id_vars=['city','area'] kar dun to kya hoga?
# (Think: id columns fixed rehte)
m=df.melt(id_vars=["area"],var_name="product",value_name="Sales")
m

Error hogi .

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['area']"

In [26]:
# Q11. Melt ke baad pivot karke original table recover karo.
# (i.e. melt → pivot → original)
m=df.melt(id_vars="city",var_name="product",value_name="Sales")
s=m.pivot_table(index="city",columns="product",values="Sales")
print(m)
print(s)

     city product  Sales
0   Delhi       A    100
1  Mumbai       A     80
2   Delhi       B    150
3  Mumbai       B    120
4   Delhi       C    200
5  Mumbai       C    140
product      A      B      C
city
Delhi    100.0  150.0  200.0
Mumbai    80.0  120.0  140.0

In [38]:
# 🔥 LEVEL-4: STACK & UNSTACK
# Q12. Ye DataFrame set_index('city') karke stack() karo:
# city | A | B
# Delhi | 100 | 150
# Mumbai| 200 | 300
# → MultiIndex Series aayega?
# Kaise dikh raha?
df = pd.DataFrame({
    "city": ["Delhi","Mumbai"],
    "A": [100,200],
    "B": [150,300]
}).set_index("city")
df
print(df)
s=df.stack()
print(s)

     city    A    B
0   Delhi  100  150
1  Mumbai  200  300
0  city     Delhi
   A          100
   B          150
1  city    Mumbai
   A          200
   B          300
dtype: object

In [37]:
# Q13. Ab usi series ko unstack() karo.
# Kya pivot jaisa output aaya?
s=df.unstack()
print(s)

   city
A  Delhi     100
   Mumbai    200
B  Delhi     150
   Mumbai    300
dtype: int64

In [43]:
# Q14. pivot_table ke output ko stack → unstack → stack repeat karke dekh
# (Har step me shape observe karo)
print(df)
print("**************Satck***********************")
s=df.stack()
print(s)
print("**************UnSatck***********************")
u=s.unstack()
print(u)
print("**************Satck***********************")
ss=u.stack()
print(ss)

     city    A    B
0   Delhi  100  150
1  Mumbai  200  300
**************Satck***********************
0  city     Delhi
   A          100
   B          150
1  city    Mumbai
   A          200
   B          300
dtype: object
**************UnSatck***********************
     city    A    B
0   Delhi  100  150
1  Mumbai  200  300
**************Satck***********************
0  city     Delhi
   A          100
   B          150
1  city    Mumbai
   A          200
   B          300
dtype: object

In [53]:
# Q15. Ye DataFrame lo:
# id | name | score_2021 | score_2022 | score_2023
# 1    A       90           92           95
# 2    B       88           90           93

# → wide_to_long use karke:

# columns = score
# pattern = score_YYYY
# YEAR extract karo.

df = pd.DataFrame({
    "id":[1,2],
    "name":["A","B"],
    "score_2021":[90,88],
    "score_2022":[92,90],
    "score_2023":[95,93]
})
wtl=pd.wide_to_long(
    df,
    stubnames="score",
    i="id",
    j="year",
    sep="_"
)
print(wtl)

        name  score
id year
1  2021    A     90
2  2021    B     88
1  2022    A     92
2  2022    B     90
1  2023    A     95
2  2023    B     93

In [66]:
# 🔥 LEVEL-5: wide_to_long (Pattern Reshape)
# Q16. wide_to_long ka output fir pivot karke wapas wide table banao.
# (Logic Ko Check karo)
df
s=pd.wide_to_long(df,stubnames="score",i="id",j="Year",sep="_")
print(s)
p=s.pivot_table(index="id",columns="Year",values="score")
print(p)

        name  score
id Year
1  2021    A     90
2  2021    B     88
1  2022    A     92
2  2022    B     90
1  2023    A     95
2  2023    B     93
Year  2021  2022  2023
id
1     90.0  92.0  95.0
2     88.0  90.0  93.0

In [ ]:
# 🔥 LEVEL-6: Trick / Concept Tests
# Q17. Pivot table default aggfunc kya hota hai?
# (mean or sum?)
mean

In [ ]:
# Q18. Melt summary banata hai ya sirf structure change karta hai?
structure chnage krta h

In [ ]:
# Q19. Stack kahe direction me reshape karta hai?
# (columns → index OR index → columns?)
column-->index

In [ ]:
# Q20. Pivot table missing combinations ko NaN fill karta hai: why?

In [ ]:
# Q21. Unpivot (melt) ke baad rows zyada hoti hain ya kam?
jyada ho jati h (wide to long)

In [72]:
# 🔥 LEVEL-7: REAL BUSINESS SCENARIOS
# Q22. Sales dataset:
# Date | Product | Region | Sales
# → Region rows me
# → Product columns me
# → Sales sum karo
import pandas as pd

df22 = pd.DataFrame({
    'Date': ['2024-01-01','2024-01-01','2024-01-01','2024-01-01','2024-01-02','2024-01-02'],
    'Product': ['A','B','A','B','A','B'],
    'Region': ['North','North','South','South','North','South'],
    'Sales': [100,150,200,250,120,300]
})
df=pd.pivot_table(df22,index="Region",columns="Product",values="Sales",aggfunc="sum")
print(df)

Product    A    B
Region
North    220  150
South    200  550

In [81]:
# Q23. Multi-year dataset:
# id | math_2021 | math_2022 | eng_2021 | eng_2022
# → wide_to_long se subject + year column banao.
df23 = pd.DataFrame({
    'id': [1,2,3],
    'math_2021': [90,88,75],
    'math_2022': [92,90,78],
    'eng_2021': [85,80,70],
    'eng_2022': [88,82,73]
})

d=pd.wide_to_long(df23, stubnames=["math","eng"], i="id", j="year", sep="_")

print(d)

         math  eng
id year
1  2021    90   85
2  2021    88   80
3  2021    75   70
1  2022    92   88
2  2022    90   82
3  2022    78   73

In [85]:
# Q24. Kisi employee ke quarterly performance ho:
# emp | q1 | q2 | q3 | q4 |
# → melt → long
# → groupby(season)
# → pivot → summary
df24 = pd.DataFrame({
    'emp': ['A','B','C'],
    'q1': [80,70,95],
    'q2': [85,72,92],
    'q3': [90,75,94],
    'q4': [88,78,96]
})
m = df24.melt(id_vars="emp", var_name="quarter", value_name="score")
m["season"] = m["quarter"].str[0]   # Q1->1
summary = m.groupby("season")["score"].mean()
df24
print(summary)

season
q    84.583333
Name: score, dtype: float64

In [ ]:
# Q25. CSV file jisme 50 columns hain Q1_2020, Q2_2020 … Q4_2023
# → Kaun sa method sabse best? (Hint: wide_to_long)
wide_to_long

In [ ]:
# LEVEL-8: CHALLENGE / ADVANCED (Interview Level)
# Q26. Agar pivot table me index me multiple columns ho (city, year) & columns me (product, category) ho — shape kaise change hoti?

In [88]:
# Q27. GroupBy + unstack + fillna + melt ka combination likho
# (Full transformation pipeline)
df = pd.DataFrame({
    "city": ["Delhi","Mumbai"],
    "A": [100,80],
    "B": [150,120],
    "C": [200,140]
})

(
 df.groupby(["city","product"])["sales"].sum()
   .unstack()
   .fillna(0)
   .melt(ignore_index=False)
)

KeyError: 'Column not found: sales'

In [93]:
# Q28. pivot_table se margins remove karke row % or column % nikalna
# (relative contribution)
df=pd.DataFrame({
    "city":["Delhi","Delhi","Delhi","Mumbai","Mumbai","Mumbai"],
    "product":["A","A","B","A","A","B"],
    "Sales":[100,80,120,200,200,300]
})
p=df.pivot_table(index="city",columns="product",values="Sales",aggfunc="sum")
row_pct = p.div(p.sum(axis=1), axis=0)
col_pct = p.div(p.sum(axis=0), axis=1)
print(row_pct)
print(col_pct)

product         A         B
city
Delhi    0.600000  0.400000
Mumbai   0.571429  0.428571
product         A         B
city
Delhi    0.310345  0.285714
Mumbai   0.689655  0.714286

In [ ]:
# Q29. unstack() karne ke baad columns MultiIndex aa jaye —
# usko flatten kaise karoge?

In [ ]:
# Q30. Aisa scenario batao jisme melt → pivot → stack → wide_to_long
# chaaro use honge.

# DATE AND TIME HANDLING

In [98]:
import pandas as pd
dates = ["2023-01-10", "2024-05-21", "2025-12-12"]
df=pd.DataFrame({"Date_string":dates})
# convert
df["Dates"]=pd.to_datetime(df["Date_string"])
print(df["Dates"])

0   2023-01-10
1   2024-05-21
2   2025-12-12
Name: Dates, dtype: datetime64[ns]